from pathlib import Path
import json,hashlib,subprocess
ROOT=Path('/Users/kaiya/Documents/Codex/2026-09-20/mo/work/rock-mini200-e1')
OUT=Path('/Users/kaiya/Documents/Codex/2026-09-21/codex-threads-01a0bc41-ceb2-72a0-8417/work/colony_v1')

def cap(id,name,maturity,paths,actual,reuse,missing):
 return dict(id=id,name=name,maturity=maturity,evidence=[dict(path=str(ROOT/p),sha256=hashlib.sha256((ROOT/p).read_bytes()).hexdigest()) for p in paths],actual=actual,reuse=reuse,colony_gap=missing,flight_or_colony_qualified=False)
cs=[
cap('OS01','Platform 登録・権限・承認','runtime_source_inspected_and_recorded_apk_acceptance', ['android/core/src/main/java/dev/rock/core/platform/PlatformStore.java','contracts/platform-api.json','docs/platform-core.md'], 'PlatformStore の component 登録、UID/署名/版の境界、PROPOSED→ISSUED→CONSUMED 承認、世代変更による旧承認停止。owner/request key、payload digest、action、期限、費用上限を照合する実装。', '新規 colony component を既存 dev.rock の capability 境界へ接続。操作者の要求と装置の実行権限を分ける。', '現行の TOOL/MCP/PROVIDER と Android owner 権限を、そのまま設備管理の役職、二者承認、ローカル非常操作へ転用できない。専用契約と署名・時刻・現場優先権の実装が必要。'),
cap('OS02','Web の仕事状態・競合検査','runtime_source_and_tests_inspected_not_rerun',['lib/workflow.ts','tests/workflow.test.mjs'], 'WorkJob は active/review/completed/cancelled。command ID 冪等性、revision 競合、工程順序、sample を工程成功に数えない処理がある。', '保守作業・点検・資材調達・検査承認のUIと仕事状態に再利用。', '設計書の draft/ready/waiting/failed を全て現行 Web runtime 実装済みとしない。生命維持の高速ループ、搭載機のGNC、秒以下保証はない。'),
cap('OS03','Android Engine・Zema・固定 Local AI plan','runtime_source_inspected_and_recorded_physical_apk_evidence',['android/core/src/main/java/dev/rock/core/Engine.java','android/automation/src/main/java/dev/rock/automation/ZemaOrchestrator.java','android/tool-sdk/src/main/java/dev/rock/sdk/ZemaToolPlan.java','docs/evidence/android-pixel-10-prefull-physical-20260916.json'], 'SQLite 上の work/run/event、選択済み Tool token、固定 article-preparation@1 入力の非信頼 planner と独立検証。Pixel APK記録は2工程、実再起動、結果・履歴回復を含む。', '操作者の要求を説明可能な有限作業へ整える構造。AIは提案だけを返し、機械検証後に仕事を生成。', '汎用設備プランナー、最適運転、異常診断の物理妥当性は未実装・未受入。LLMを直接 actuator に接続しない。'),
cap('OS04','MCP Broker の永続状態・結果不明照合','runtime_source_and_owned_fixture_tests_inspected_not_rerun',['systems/rock-star-os/os/mcp_broker/broker.py','systems/rock-star-os/tests/test_mcp_broker_core.py','systems/rock-star-os/tests/test_mcp_broker_lifecycle.py'], 'Private SQLite、FULL同期、単一writer flock、subject/device/alias/epoch、immutable consent、容量上限。sending 再起動後は unknown、送信claim済みは execute を再送せず reconcile を使用。', '遅延・切断を伴う設備への指令意図と照合の考え方を再利用。capability の有限集合と generation fence を維持。', '現行は所有fixture中心。物理装置の at-most-once 作用保証、時刻同期、実無線、宇宙リンク、複数拠点 consensus は提供しない。'),
cap('OS05','MCP Runtime の fixture 明示','runtime_source_inspected',['systems/rock-star-os/os/mcp_broker/runtime.py'], 'runtime metadata は simulation_only=true/provider_connected=false。再開時の authority・設定・CA hash・保存fileを確認し、履歴欠損を新規状態として自動初期化しない。', 'SIM_ONLY と実機接続状態を外観上も契約上も分離する方式。保持履歴喪失時の閉鎖を新設計にも使う。', '本番Provider、機器認証局、コロニー内認証局、衛星間切替は未接続。'),
cap('OS06','SQLite データ保存境界','runtime_source_and_design_inspected',['docs/data-storage-boundaries.md','systems/rock-star-os/src/blackberryrock/storage.py','android/core/src/main/resources/schema.sql'], 'Web D1、Operator Dock D1、Wallet、Android Engine、Android Platform を異なる正本として分離。Store に冪等job・制限された状態遷移とSQLite WAL。', '運用指令台帳、telemetry、資材台帳、操作者私有データを別に保管し用途ごとの retention を定義。', '既存金融台帳を酸素・水・電力計測に流用しない。多拠点 replication、長期断線、測定時刻品質、校正情報、災害復旧は追加が必要。'),
cap('OS07','Backup と復元後の権限停止','runtime_source_inspected_and_recorded_partial_physical_evidence',['android/core/src/main/java/dev/rock/core/platform/EncryptedBackup.java','android/core/src/main/java/dev/rock/core/platform/PlatformStore.java','contracts/platform-api.json','docs/evidence/android-pixel-10-prefull-physical-20260916.json'], 'AES-GCM backup、独立回復secret、空のowner対象へのtransaction復元、automation停止、Sky token rotation、旧承認停止、component authorityを復元しない。Pixelはhardware-backed exportと非破壊再起動の記録。', '復元を新たな設備操作権限として扱わず、ローカル監査を経て再有効化する。', 'Pixel全損・Keystore喪失の実機復旧は未実施。コロニー冗長ノード、全拠点喪失、長期オフライン鍵回復、RT制御の無停止切替は未受入。'),
cap('OS08','Linux/QEMU A/B更新・復旧','source_present_and_recorded_qemu_candidate_evidence',['systems/rock-star-os/os/update/rock_update.py','data/qemu-release-audit.json','docs/rockstaros-1.0-architecture.md'], 'rc2 b7d819cd候補のA/B更新、失敗rollback、backup、current-copy二重使用防止の内部証拠を記録。開発鍵、draft_not_public。', '監督端末のイメージ署名、互換schema確認、段階更新、失敗回復のパターン。', '正式署名、最終同一候補受入、flight computer、耐放射線メモリ、宇宙環境、停電/部分故障の生存性は未証明。現在HEADの全機能がrc2に含まれるとは言えない。'),
cap('OS09','Tool package・隔離Runner・Registry','runtime_source_present_design_and_records_inspected',['systems/rock-star-os/os/runner/README.md','systems/rock-star-os/os/runner/executor.py','systems/rock-star-os/os/registry/README.md','systems/rock-star-os/os/registry/client.py','docs/rockstaros-1.0-architecture.md'], '署名manifest、有限recipe、hash/期限/失効検査、実行隔離とresource制限のLinux系実装。接続先はfixtureの範囲を持つ。', '保守Toolと分析Toolの配布、版固定、権限差分、sandbox分離。', '宇宙搭載機に対するWCET・RT scheduling・認定toolchain・故障隔離保証はない。一般Toolの導入が設備制御権限を増やさない接続審査が必要。'),
cap('OS10','Operator Agent の限定署名命令','source_present_and_recorded_partial_apk_evidence',['android/operator-agent/src/main/java/dev/rock/operator/agent/OperatorCommandVerifier.java','android/operator-agent/src/main/java/dev/rock/operator/agent/OperatorCommandExecutor.java','docs/evidence/android-pixel-10-prefull-physical-20260916.json'], '署名、replay、monotonic counterのAndroid試験記録。Device Owner無しのfactory resetは拒否。', '管理命令の出所・再送・単調counterを分ける参考。', 'これは端末管理用であり、気密扉、弁、与圧、推進制御の仕様ではない。コロニー緊急命令へそのまま転用しない。'),
cap('OS11','Decision Provider 契約','schema_design_present_generic_runtime_not_proved',['contracts/decision-provider.json','docs/rockstaros-complete-design.md'], 'requestId/ownerRef/workId/stateDigest/policyVersion、effect、offlineRequired/cloudAllowed、maxLatency/maxCost/maxAttemptsをJSON Schemaで定義。answered/abstained/blocked/failed。', 'AI予測結果を制御許可と区別する共通要求・根拠ハッシュの形を維持。', '契約ファイルは全Provider統合やcolony判断精度の証拠ではない。実設備を動かす制御則・物理限界は別の決定的コードと試験が必要。'),
cap('OS12','Material Invention sandbox','runtime_source_present_fixture_scope',['contracts/material-invention.json','lib/material-invention.ts','tests/material-invention.test.mjs'], '二物質候補・制約・単位・危険性チェックの装置非接続sandbox。契約は物理実験の承認・実行をしないと明示。', 'コロニーの研究・資材候補・発明履歴に使う上位アプリ候補。', '生命維持材、構造材、燃料、食品や水の製造適合、実材料性能を証明しない。物理simulationモデルやラボ測定は別。'),
cap('OS13','公開 Control Core','pure_reference_code_tested_this_audit',['public-release/rockstaros/packages/control-core/src/index.js','public-release/rockstaros/packages/control-core/test/index.test.js','public-release/rockstaros/packages/control-core/README.md'], 'createActionRequest/approveAction/canExecute/recordOutcome。read/write/external と succeeded/failed/interrupted/unknownを区別。今回Node単体4/4合格。', '利用者へ承認と結果の違いを示す最小参照と表示用の概念。', 'actorは文字列であり認証主体ではない。メモリ内Objectだけで、DB・暗号署名・ネットワーク・安全制御はない。READMEはreuse terms not grantedと明記。新パッケージへコピーせず契約上の考え方のみ参照。'),
cap('OS14','avokado Edge Hub のOS位置付け','hardware_concept_and_os_design_not_hardware_accepted',['README.md','docs/avocado-mini-tower20/README.md'], 'このrepoの正本は4本の銀色200mm Motion Towerと別Edge Hub。RockstarOSが入力、AI、作品、権限、履歴を管理する製品構想。', 'コロニーのローカル表示・生活UI・作業計画端末。通信断でも現地状況と未確認命令を区別する。', 'avokado実機受入なし。現repoより新しいE3成果物が別作業にあるため、寸法・電力部品はそちらの版を別途参照。生活端末を単独の生命維持安全装置にしない。'),
]
gaps=[
 ('G01','故障しても生命維持を続ける層','RockstarOS監督機、通信、AIが停止しても現地安全制御器が動き続ける。watchdog、独立電源、最低機能、手動切替と隔離を設備ごとに設計・実測。'),
 ('G02','設備ドライバと意味','O2/CO2、圧力、水、電力、熱、火災、気密扉の telemetry/capability を単位・測定時刻・品質・校正・許容域付きで定義。値は対象設備から決める。'),
 ('G03','リアルタイム性能と環境','deadline、最悪実行時間、jitter、電磁、真空/熱/振動/放射線、SEU対策は監督OSと安全制御器それぞれに要求・試験が必要。'),
 ('G04','複数拠点と断線','site/node identity、store-and-forward、priority/TTL/expiry、telemetry stale判定、clock品質、単一command authorityとfencingを定義。リンク復帰で期限切れ指令を実行しない。'),
 ('G05','多人数の権限','現在のownerモデルからcrew/operator/maintenance/medical/safetyを別に設計。緊急手動権限と事前承認された自動応答は毎回Web承認を待たない。'),
 ('G06','資源と可用性','総発電/蓄電/ピーク、最低換気・水・熱余裕、冗長性、故障時の負荷遮断順を実設備モデルで算定。合成simから人命維持日数を保証しない。'),
 ('G07','搭載系と地上系の分離','ロケット flight/GNC、衛星TT&C、コロニー環境制御、avokado住民UIの安全境界を分ける。RockstarOS共通管理を単一故障点にしない。'),
 ('G08','署名・復旧・更新の現地運用','offline信頼根、鍵失効・交換、rollback/data互換、更新中の現地制御維持、事故ログ保存、物理改ざんを最終機体で受入。'),
 ('G09','受入証拠','単体→ソフト閉ループ→controller HIL→装置試験→無人実証→有人運用の証拠を別に保存。現在の数十/数百テスト数はコロニー適合率ではない。'),
]
interfaces={
 'proposed_component_id':'dev.rock.colony.supervisor',
 'proposed_python_module':'rockstaros_colony_sim',
 'proposed_schemas':['rockstaros-colony-command/1','rockstaros-colony-telemetry/1','rockstaros-colony-receipt/1','rockstaros-colony-policy/1'],
 'scope':'new standalone simulation contract; not yet a native Platform API extension or merged RockstarOS component',
 'required_command_fields':['schema','commandId','requestId','ownerRef','siteId','nodeId','workId','componentId','componentGeneration','capability','payload','payloadDigest','policyVersion','expectedRevision','issuedAt','expiresAt','mode'],
 'required_telemetry_fields':['schema','siteId','nodeId','sensorId','sequence','observedAt','receivedAt','clockQuality','value','unit','quality','calibrationRef','simulated'],
 'recommended_receipt_states':['prepared','blocked','queued','dispatched','acknowledged','succeeded','failed','cancelled','expired','unknown'],
 'receipt_semantics':'accepted_locally != delivered != acknowledged != physical_effect_verified; acknowledged alone never means succeeded',
 'safety_modes':['SIM_ONLY','READ_ONLY','COMMISSIONING','OPERATE'],
 'initial_mode':'SIM_ONLY',
 'initial_hardware_effect_allowed':False,
 'native_mapping':{'ownerRef':'Android Platform owner / authenticated Linux principal subject','nodeId':'device_ref with explicit site binding','componentGeneration':'PlatformStore generation / Broker connection epoch; not interchangeable without adapter','workId':'existing Work/Engine job identity','commandId':'per-intent idempotency key, same ID with changed payload is conflict','unknown':'preserve existing MCP unknown and public Control Core unknown; do not auto-convert to failed'},
 'standalone_design_tests':['duplicate same command returns retained receipt','changed payload for same command rejected','stale telemetry cannot authorize unsafe increase','expired command rejected after offline queue','AI proposal cannot bypass policy','dispatched command interrupted becomes unknown, never automatically resent','generation change fences queued old command','local controller continues when supervisor or satellite link unavailable','restore clears actuation authority until recommissioned','sim receipt never claims hardware effect'],
 'do_not_copy':['Public Control Core has no reuse permission grant; new simulation may implement fresh code with separately documented contract','Do not change existing crypto domain or backup schema names from older AvocadoOS evidence merely to rename products']
}
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()
status=subprocess.check_output(['git','status','--porcelain'],cwd=ROOT,text=True)
data={'schema':'rockstaros-colony-reuse-audit/1','audited_at':'2026-09-23','repository':str(ROOT),'head':head,'branch':subprocess.check_output(['git','branch','--show-current'],cwd=ROOT,text=True).strip(),'working_tree_clean':not status,'remote_freshness':'not_checked_no_network_per_task_scope','audit_scope':'read-only source and retained evidence audit; no original repository edits, no network, no hardware or invasive integration','new_test':{'name':'public control-core pure Node tests','passed':4,'failed':0,'hardware':False,'network':False},'capabilities':cs,'missing_colony_requirements':[{'id':x,'title':y,'required_work':z} for x,y,z in gaps],'proposed_interfaces':interfaces,'summary':'RockstarOS can be the colony supervisory and operator information core after substantial new engineering; no inspected artifact proves colony safety control or flight readiness.'}
(OUT/'os_inventory.json').write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
lines=['# RockstarOS コロニー中核化の実装監査','', '2026-09-23 / 読取監査。対象repoは変更していない。','', f'対象: `{ROOT}`',f'HEAD: `{head}` / branch `{data["branch"]}` / clean: `{data["working_tree_clean"]}`','', '**結論: RockstarOSには使える運用基盤の実コードがある。コロニーの中核を、操作者・仕事・権限・記録・通信をまとめる監督層として構築できる。ただし、生命維持、電源保護、飛行制御の実装・認定が既にあるという意味ではない。**','', 'この監査ではネットワーク・GitHub照合・原repo編集・端末操作・実機試験を実施していない。リポジトリの保存証拠と今回のコード確認を区別する。','', '## 1. 今回と過去の証拠','', '- 今回再実行: 公開 Control Core の純粋な Node 単体テスト 4/4。外部通信・実機なし。','- 過去の保存証拠: QEMU rc2 の開発鍵による起動、A/B、復旧。対象sourceは b7d819cd 系で、今回HEAD全体の再受入ではない。','- 過去の保存証拠: Pixel 10 / GL066 の試験署名APK、2工程Tool、保存、実再起動、暗号化backup export。完成OS image、flash、OTA、全損復旧の受入ではない。','- OS本文の全体状態図や計画を、個別runtimeの実装済み状態へ読み替えない。','', '## 2. 再利用する実装と不足','']
for c in cs:
 lines += [f'### {c["id"]} {c["name"]}', '', f'証拠段階: `{c["maturity"]}`', '', f'**確認したこと:** {c["actual"]}', '', f'**再利用:** {c["reuse"]}', '', f'**不足:** {c["colony_gap"]}', '', '根拠: '+ ' / '.join('`'+str(Path(e['path']).relative_to(ROOT))+'`' for e in c['evidence']), '']
lines+=['## 3. 新しいコロニー監督モジュールの境界','', '新規 component ID は `dev.rock.colony.supervisor`、独立試作の module は `rockstaros_colony_sim` を提案する。これは既存OSに組込み済みの名前ではない。実装はこの設計作業の別フォルダへ置き、元repoへ無断コピー・mergeしない。','', 'schemaは `rockstaros-colony-command/1`、`telemetry/1`、`receipt/1`、`policy/1` をそれぞれ完全名で版管理する。`contracts/platform-api.json` の既存apiVersionを暗黙変更しない。','', '命令必須field: '+', '.join('`'+x+'`' for x in interfaces['required_command_fields'])+'。','', '測定必須field: '+', '.join('`'+x+'`' for x in interfaces['required_telemetry_fields'])+'。','', '保存時の受付、通信相手の受領、実作用の完了確認を分ける。`acknowledged`だけで`succeeded`にしない。送信後に結果不明になった指令は、同じ作用を再送せず、機器側の照会/現地確認へ進める。','', 'SIM_ONLYを初期値とし、physical effectはfalse固定。SIM_ONLY・READ_ONLY・COMMISSIONING・OPERATEの切替は設計上の将来状態であり、この試作が実機へ接続できることを意味しない。','', 'LLMは要約・比較・計画候補。許容範囲・期限・現在状態を確定コードが確認する。安全系の自動応答は、通信やWeb画面の承認待ちで止めない。安全域は本物の設備から決定し、例示閾値を飛行/生命維持値と呼ばない。','', '## 4. 新規開発が必要な領域','']
for id,title,req in gaps: lines += [f'- **{id} {title}:** {req}']
lines+=['','## 5. 独立試作で検証する契約','']+[f'- {x}' for x in interfaces['standalone_design_tests']]+['','## 6. 成果の読み方','', '原repoの更新日と今回の設計版を混ぜない。4/4は公開参照関数のロジックテストであり、飛行、ハード、衛星、生命維持の合格数ではない。今後追加するcolony simulationの成功も、その仮定と状態機械の範囲に限定する。','', '公開Control Core READMEは再利用許諾未付与と記すため、そのソースを新規成果物へコピーしない。この監査は自分のシステムを設計するための実装確認であり、外部へのライセンス許諾や公開を追加しない。','']
(OUT/'os_inventory.md').write_text('\n'.join(lines))
print(json.dumps({'capabilities':len(cs),'gaps':len(gaps),'clean':not status,'outputs':[str(OUT/'os_inventory.md'),str(OUT/'os_inventory.json')]},ensure_ascii=False))
