import test from 'node:test';
import { execFileSync } from 'node:child_process';
import { constants } from 'node:fs';

const moduleUrl = new URL('../scripts/amc-parallel.mjs', import.meta.url).href;
const posix = {
  skip: !Number.isInteger(constants.O_NOFOLLOW) || constants.O_NOFOLLOW === 0 ||
    !Number.isInteger(constants.O_NONBLOCK) || constants.O_NONBLOCK === 0,
};

// Each scenario has a separate process so its filesystem hooks cannot affect
// other tests. Fixtures contain only generated bytes and temporary Git metadata.
function scenario(body) {
  const source = `
    import assert from 'node:assert/strict';
    import fs from 'node:fs';
    import { createHash } from 'node:crypto';
    import { execFileSync } from 'node:child_process';
    import { syncBuiltinESMExports } from 'node:module';
    import { tmpdir } from 'node:os';
    import { join } from 'node:path';
    const { workspaceSnapshot } = await import(process.argv[1]);
    const original = Object.fromEntries(
      ['openSync', 'closeSync', 'readFileSync', 'lstatSync', 'fstatSync', 'realpathSync']
        .map((key) => [key, fs[key]]),
    );
    const root = fs.realpathSync(fs.mkdtempSync(join(tmpdir(), 'amc-snapshot-')));
    const repo = join(root, 'repo');
    fs.mkdirSync(repo);
    execFileSync('git', ['init', '-q'], { cwd: repo });
    const file = join(repo, 'input.bin');
    const outside = join(root, 'outside.bin');
    const input = Buffer.from([0, 255, 1, 13, 10, 128]);
    const other = Buffer.from('synthetic outside bytes');
    fs.writeFileSync(file, input);
    fs.writeFileSync(outside, other);
    execFileSync('git', ['add', 'input.bin'], { cwd: repo });
    const digest = (bytes) => createHash('sha256').update(bytes).digest('hex');
    let targetFd;
    let targetReads = 0;
    fs.openSync = (path, ...args) => {
      const fd = original.openSync(path, ...args);
      if (path === file) targetFd = fd;
      return fd;
    };
    fs.readFileSync = (path, ...args) => {
      if (path === file || path === targetFd) targetReads++;
      return original.readFileSync(path, ...args);
    };
    const install = () => syncBuiltinESMExports();
    const closed = () => {
      assert.equal(typeof targetFd, 'number');
      assert.throws(() => original.fstatSync(targetFd), { code: 'EBADF' });
    };
    // Trigger only after the real containment check returns its original path.
    const afterContainment = (mutate, target = file) => {
      let used = false;
      fs.realpathSync = (path, ...args) => {
        const result = original.realpathSync(path, ...args);
        if (path === target && !used) { used = true; mutate(); }
        return result;
      };
    };
    try {
      ${body}
    } finally {
      Object.assign(fs, original);
      syncBuiltinESMExports();
      fs.rmSync(root, { recursive: true, force: true });
    }
  `;
  return execFileSync(process.execPath, ['--input-type=module', '-e', source, moduleUrl], {
    encoding: 'utf8', timeout: 5000, stdio: ['ignore', 'pipe', 'pipe'],
  });
}

void test('snapshots binary, dirty and untracked files, ignores caches, preserves deleted tracked null', posix, () => {
  scenario(`
    fs.writeFileSync(file, Buffer.concat([input, Buffer.from('dirty')]));
    fs.writeFileSync(join(repo, '.gitignore'), 'cache/\\n');
    fs.mkdirSync(join(repo, 'cache'));
    fs.writeFileSync(join(repo, 'cache/ignored.bin'), other);
    fs.writeFileSync(join(repo, 'untracked.bin'), input);
    fs.writeFileSync(join(repo, 'deleted.bin'), input);
    execFileSync('git', ['add', 'deleted.bin'], { cwd: repo });
    fs.unlinkSync(join(repo, 'deleted.bin'));
    install();
    const result = workspaceSnapshot(repo);
    assert.equal(result['input.bin'], digest(Buffer.concat([input, Buffer.from('dirty')])));
    assert.equal(result['untracked.bin'], digest(input));
    assert.equal(result['deleted.bin'], null);
    assert.equal(Object.hasOwn(result, 'cache/ignored.bin'), false);
    closed();
  `);
});

void test('rejects a final-component symlink installed after containment without reading it', posix, () => {
  scenario(`
    afterContainment(() => { fs.unlinkSync(file); fs.symlinkSync(outside, file); });
    install();
    assert.throws(() => workspaceSnapshot(repo), { code: 'ELOOP' });
    assert.equal(targetReads, 0);
  `);
});

void test('rejects a different regular-file inode installed after containment before reading', posix, () => {
  scenario(`
    afterContainment(() => { fs.renameSync(file, join(root, 'old.bin')); fs.writeFileSync(file, other); });
    install();
    assert.throws(() => workspaceSnapshot(repo), /changed during snapshot/);
    assert.equal(targetReads, 0);
    closed();
  `);
});

void test('rejects a parent-directory symlink replacement after containment before reading', posix, () => {
  scenario(`
    const parent = join(repo, 'nested');
    fs.mkdirSync(parent);
    const nested = join(parent, 'tracked.bin');
    fs.writeFileSync(nested, input);
    execFileSync('git', ['add', 'nested/tracked.bin'], { cwd: repo });
    const external = join(root, 'external');
    fs.mkdirSync(external);
    fs.writeFileSync(join(external, 'tracked.bin'), other);
    let nestedFd;
    let nestedReads = 0;
    fs.openSync = (path, ...args) => {
      const fd = original.openSync(path, ...args);
      if (path === nested) nestedFd = fd;
      return fd;
    };
    fs.readFileSync = (path, ...args) => {
      if (path === nested || path === nestedFd) nestedReads++;
      return original.readFileSync(path, ...args);
    };
    afterContainment(() => {
      fs.renameSync(parent, join(root, 'original-parent'));
      fs.symlinkSync(external, parent);
    }, nested);
    install();
    assert.throws(() => workspaceSnapshot(repo), /changed during snapshot/);
    assert.equal(nestedReads, 0);
    assert.throws(() => original.fstatSync(nestedFd), { code: 'EBADF' });
  `);
});

void test('hashes the checked descriptor when its pathname changes after fstat', posix, () => {
  scenario(`
    fs.fstatSync = (fd, ...args) => {
      const result = original.fstatSync(fd, ...args);
      if (fd === targetFd) {
        fs.renameSync(file, join(root, 'opened.bin'));
        fs.symlinkSync(outside, file);
      }
      return result;
    };
    install();
    assert.equal(workspaceSnapshot(repo)['input.bin'], digest(input));
    assert.equal(targetReads, 1);
    closed();
  `);
});

void test('rejects a FIFO installed after containment without blocking or reading', posix, () => {
  scenario(`
    afterContainment(() => {
      fs.unlinkSync(file);
      execFileSync('mkfifo', [file]);
    });
    let flags;
    fs.openSync = (path, ...args) => {
      const fd = original.openSync(path, ...args);
      if (path === file) { targetFd = fd; flags = args[0]; }
      return fd;
    };
    install();
    assert.throws(() => workspaceSnapshot(repo), /changed during snapshot/);
    assert.equal(flags & fs.constants.O_NONBLOCK, fs.constants.O_NONBLOCK);
    assert.equal(flags & fs.constants.O_NOFOLLOW, fs.constants.O_NOFOLLOW);
    assert.equal(targetReads, 0);
    closed();
  `);
});

for (const stage of ['fstatSync', 'readFileSync']) {
  void test('closes the opened file when ' + stage + ' fails', posix, () => {
    scenario(`
      const stage = ${JSON.stringify(stage)};
      fs[stage] = (fd, ...args) => {
        if (fd === targetFd) throw new Error('injected read failure');
        return original[stage](fd, ...args);
      };
      install();
      assert.throws(() => workspaceSnapshot(repo), /injected read failure/);
      closed();
    `);
  });
}

void test('rejects an existing escaping parent symlink and existing leaf symlinks', posix, () => {
  scenario(`
    fs.unlinkSync(file);
    fs.symlinkSync(outside, file);
    install();
    assert.throws(() => workspaceSnapshot(repo), /requires regular files/);
    assert.equal(targetReads, 0);
    fs.unlinkSync(file);
    fs.symlinkSync(join(root, 'missing.bin'), file);
    assert.throws(() => workspaceSnapshot(repo), /requires regular files/);
    fs.unlinkSync(file);
    fs.writeFileSync(file, input);
    const nested = join(repo, 'nested');
    fs.mkdirSync(nested);
    fs.writeFileSync(join(nested, 'file.bin'), input);
    execFileSync('git', ['add', 'nested/file.bin'], { cwd: repo });
    fs.renameSync(nested, join(root, 'external'));
    fs.symlinkSync(join(root, 'external'), nested);
    fs.writeFileSync(join(repo, '.git/info/exclude'), 'nested\\n');
    assert.throws(() => workspaceSnapshot(repo), /escapes repository/);
  `);
});
