import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

const root = process.cwd();
const read = (path) => readFileSync(resolve(root, path), 'utf8');

void test('public RockstarOS entry offers SIM/eSIM-led service access without claiming current availability', () => {
  const marketing = read('sites/avocado-mini/src/pages/index.astro');
  const onboarding = read('app/connect/page.tsx');
  const projectMap = read('PROJECTS.md');
  const claimUI = read('components/rockstar-entitlement-claim.tsx');
  const offerProfiles = read('lib/rockstar-service-offers.ts');
  const offerProfileTests = read('tests/rockstar-service-offers.test.mjs');
  const entitlementApi = read('app/api/rockstar/entitlements/route.ts');
  const claimPackage = read('lib/rockstar-entitlement-package.ts');
  const launch = read('app/rockstaros/page.tsx');
  const home = read('components/home-screen.tsx');
  const skyMarketplace = read('components/sky-marketplace.tsx');
  const workbench = read('components/workbench.tsx');
  const packageHandoff = read('lib/rockstar-package-handoff.ts');
  const packageHandoffTests = read('tests/rockstar-package-handoff.test.mjs');
  const packageRuntime = read('lib/sky-package-runtime.ts');
  const packageRuntimeTests = read('tests/sky-package-runtime.test.mjs');
  const mcpRunner = read('components/mcp-bot-runner.tsx');
  const workflow = read('lib/workflow.ts');
  const skyMarketplacePage = read('app/sky/marketplace/page.tsx');
  const includedPackageAccess = read('lib/rockstar-service-package-access.ts');
  const includedPackageAccessTests = read('tests/rockstar-service-package-access.test.mjs');
  const commerce = read('lib/sky-commerce.ts');
  const commerceTests = read('tests/sky-commerce.test.mjs');
  const deviceHome = read('app/api/rockstar/device-home/route.ts');
  const remoteAiWorker = read('services/sky-agent-runtime/src/worker.ts');
  const deviceTransport = read('android/automation/src/main/java/dev/rock/automation/AndroidRockstarDeviceHomeTransport.java');
  const shellApi = read('android/shell-api/src/main/aidl/dev/rock/shellapi/IShellApi.aidl');
  const shellUi = read('android/shell/src/main/java/dev/rock/shell/MainActivity.java');
  const shellConnection = read('android/shell/src/main/java/dev/rock/shell/ShellConnection.java');
  const shellService = read('android/automation/src/main/java/dev/rock/automation/RockShellService.java');
  const recoveryBinding = read('android/core/src/main/java/dev/rock/core/platform/A2ARecoveryBinding.java');
  const recoveryBindingTest = read('android/core/src/test/java/dev/rock/core/platform/A2ARecoveryBindingTest.java');
  const delegationApi = read('app/api/sky/a2a-delegations/[id]/route.ts');
  const delegationReadApi = delegationApi.slice(
    delegationApi.indexOf('export async function GET'),
    delegationApi.indexOf('export async function PATCH'),
  );
  const brokerEnrollment = read('android/automation/src/main/java/dev/rock/automation/AndroidA2ABrokerEnrollment.java');
  const brokerTransport = read('android/automation/src/main/java/dev/rock/automation/AndroidA2ABrokerDeviceTransport.java');
  const brokerKeyStore = read('android/automation/src/main/java/dev/rock/automation/A2ABrokerDeviceKeyStore.java');
  const shellCurrencyFormatter = read('android/shell/src/main/java/dev/rock/shell/UsageCurrencyFormatter.java');
  const usageTrustConfig = read('android/automation/src/main/java/dev/rock/automation/AndroidA2AUsageTrustConfig.java');
  const a2aJson = read('android/automation/src/main/java/dev/rock/automation/AndroidA2AJson.java');
  const rockApplication = read('android/automation/src/main/java/dev/rock/automation/RockApplication.java');
  const automationGradle = read('android/automation/build.gradle');

  for (const source of [marketing, onboarding, launch]) {
    assert.match(source, /SIM[ /]+eSIM|physical SIM|物理SIM/i);
    assert.match(source, /RockstarOS/);
    assert.match(source, /Sky/);
    assert.match(source, /Zema/);
  }
  assert.match(marketing, /carriers, device retailers and online channels/);
  assert.match(marketing, /physical SIM or eSIM/i);
  assert.match(marketing, /binary does not live on the SIM/);
  assert.match(marketing, /app or browser client/);
  assert.match(marketing, /not available yet/);
  assert.match(onboarding, /共通ログイン|同じアカウント/);
  assert.match(onboarding, /利用開始後の主な入口/);
  assert.match(onboarding, /Agent Workbench — 依頼・進捗・費用/);
  assert.match(onboarding, /見積や実行料金が確認できない場合は、有料実行を開始しません/);
  assert.match(onboarding, /販売チャネル共通の購入claim発行と利用開始は準備中/);
  assert.match(onboarding, /物理SIM\/eSIMは通信事業者・Rockstar直販・端末販売店・オンライン販売/);
  assert.match(onboarding, /購入・通信開通/);
  assert.match(onboarding, /RockstarOSサービス利用権/);
  assert.match(onboarding, /eSIMプランカタログは契約・販売条件の調査用/);
  assert.match(projectMap, /SIM\/eSIM-led RockstarOS service offer/);
  assert.doesNotMatch(projectMap, /eSIM専用製品の利用開始/);
  assert.doesNotMatch(onboarding, /対応eSIMプランを確認する/);
  assert.match(onboarding, /Rockstar IDに一度だけ登録する/);
  assert.match(onboarding, /署名済み購入claim/);
  assert.match(onboarding, /見積と上限を承認したCloud作業は端末がオフラインでも続き/);
  assert.match(onboarding, /<RockstarEntitlementClaim \/>/);
  assert.match(claimUI, /claimRedemptionAvailable/);
  assert.match(claimUI, /type="file" accept="application\/json,\.json"/);
  assert.match(claimUI, /販売元から受け取った利用開始リンクを開くと/);
  assert.match(claimUI, /parseRockstarEntitlementPackage/);
  assert.match(claimUI, /parseRockstarEntitlementHandoffFragment/);
  assert.match(claimUI, /この販売offerの初期Agent構成/);
  assert.match(claimUI, /端末での導入・実行は利用者の確認後/);
  assert.match(claimUI, /Sky Marketplace/);
  assert.match(claimUI, /sky\/marketplace\?package=/);
  assert.match(skyMarketplacePage, /searchParams: Promise/);
  assert.match(skyMarketplacePage, /initialPackageKey=/);
  assert.match(skyMarketplace, /item\.packageKey === initialPackageKey/);
  assert.match(skyMarketplace, /この購入に含まれるPackageは現在の審査済みRegistryにありません/);
  assert.match(skyMarketplace, /Packageの現在の審査状態を確認できません/);
  assert.match(skyMarketplace, /fetch\('\/api\/rockstar\/entitlements'/);
  assert.match(skyMarketplace, /activePackageIncluded/);
  assert.match(skyMarketplace, /SIM\/eSIMオファーに含まれるアクセス（Cloud実行等は別料金の場合あり）/);
  assert.match(skyMarketplace, /重複購入を避けるため購入を保留しました/);
  assert.match(skyMarketplace, /Cloud実行等は別料金の場合あり/);
  assert.match(skyMarketplace, /chat\?view=work&package=/);
  assert.match(skyMarketplace, /Zemaでクラウド依頼を作る/);
  assert.match(workbench, /initialPackageKey/);
  assert.match(workbench, /\/api\/sky\/tool-registry/);
  assert.match(workbench, /\/api\/rockstar\/entitlements/);
  assert.match(workbench, /rockstarPackageHandoffMessage\(handoffPackage, task\)/);
  assert.match(workbench, /message: fullDelegationMessage/);
  assert.match(workbench, /Providerへ見積依頼として送った全文/);
  assert.match(workbench, /parseCurrencyInputToMinor\(value, current\.budgetCurrency\.trim\(\)\.toUpperCase\(\)\)/);
  assert.match(workbench, /通貨の通常単位で入力します（USD 10\.00、JPY 1,000など）/);
  assert.match(workbench, /disabled=\{Boolean\(delegationBudgetPool\)\}/);
  assert.match(workbench, /固定後に上限を増やす操作は未実装です/);
  assert.match(workbench, /a2a-result-check/);
  assert.match(workbench, /成果と利用receiptを確認済みとして記録/);
  assert.match(workbench, /compatibleLocalPackageRuntimes/);
  assert.match(packageRuntime, /canonical\(tool\.outputSchema\) === output/);
  assert.match(workbench, /完全一致する入出力Schema/);
  assert.match(workbench, /fixedToolName=/);
  assert.match(workbench, /毎回確認し、既存の1回限りの承認/);
  assert.match(packageRuntime, /manifest\.pricing\.model !== 'free'/);
  assert.match(packageRuntime, /tool\.pricing\.model === 'free'/);
  assert.match(packageRuntime, /canonical\(tool\.inputSchema\) === input/);
  assert.match(packageRuntimeTests, /exact input and output schemas/);
  assert.match(mcpRunner, /fixedToolName\?: string/);
  assert.match(packageHandoff, /manifest SHA-256/);
  assert.match(packageHandoff, /依頼仕様の参照情報です/);
  assert.match(packageHandoffTests, /pins the exact reviewed capability/);
  assert.match(workflow, /id: 'cloud-agent'/);
  assert.match(includedPackageAccess, /entitlement\.status !== 'active'/);
  assert.match(includedPackageAccessTests, /only ready packages from active included profiles/);
  assert.match(includedPackageAccessTests, /malformed or missing entitlement payloads fail closed/);
  assert.match(commerce, /isIncludedInActiveServiceOffer/);
  assert.match(commerce, /このPackageは有効なSIM\/eSIM利用権に含まれています/);
  assert.match(commerceTests, /active SIM\/eSIM offer package blocks direct Marketplace checkout on the server/);
  assert.match(commerceTests, /expired and revoked SIM\/eSIM claims do not block a legitimate package checkout/);
  assert.match(claimUI, /window\.history\.replaceState/);
  assert.match(claimUI, /リンクを開いただけでは登録されません/);
  assert.match(claimPackage, /#rockstar-claim=/);
  assert.match(claimPackage, /encodeRockstarEntitlementHandoffFragment/);
  assert.match(claimUI, /\/api\/rockstar\/entitlements/);
  assert.match(claimUI, /signin-with-chatgpt\?return_to=%2Fconnect/);
  assert.match(launch, /署名済み導入経路/);
  assert.match(home, /href="\/connect"/);
  assert.match(home, /aria-label="RockstarOSの主要サービス"/);
  assert.match(home, /href="\/sky"><Cloud/);
  assert.match(home, /href="\/chat"><MessageCircle/);
  assert.match(home, /href="\/work"><Bot/);
  assert.match(home, /href="\/work"><Bot[^]*?<strong>Agent<\/strong><span>依頼・進捗・費用・成果<\/span>/);
  assert.match(deviceHome, /requestRockstarUser\(request, db\)/);
  assert.match(deviceHome, /recentAgents/);
  assert.match(deviceHome, /recentLlm/);
  assert.match(deviceHome, /invoiceVerified: false/);
  assert.match(deviceHome, /fundedWallet: false/);
  assert.match(entitlementApi, /describeRockstarServiceOfferProfile\(/);
  assert.match(deviceHome, /entitlements: await Promise\.all\(entitlements\.slice\(0, 20\)/);
  assert.match(deviceHome, /describeRockstarServiceOfferProfile\(/);
  assert.match(offerProfiles, /const issuerId = value\.issuerId as string/);
  assert.match(offerProfiles, /const offerId = value\.offerId as string/);
  assert.match(offerProfiles, /manifestSha256 !== pin\.manifestSha256/);
  assert.match(offerProfiles, /activation: 'owner_choice_required'/);
  assert.match(offerProfileTests, /channel-neutral offer maps to its own versioned initial agent pack/);
  assert.match(offerProfileTests, /owner confirmation still required/);
  assert.match(offerProfileTests, /stale\/revoked package pins/);
  assert.match(deviceHome, /currentEstimateMinor/);
  assert.match(deviceHome, /stream_estimate/);
  assert.match(remoteAiWorker, /onOutputProgress: async \(\{ outputBytes, observedAt \}\)/);
  assert.match(remoteAiWorker, /store\.updateLiveEstimate\(ownerUserId, executionId, outputBytes, observedAt\)/);
  assert.match(shellUi, /appendServiceEntitlements\(text, home\.optJSONArray\("entitlements"\)\)/);
  assert.match(shellUi, /このRockstar IDに登録なし（上の欄から購入claimを登録）/);
  assert.match(shellUi, /端末への導入・実行は本人確認後/);
  assert.match(shellUi, /case "physical_sim": return "物理SIM"/);
  assert.match(shellUi, /case "esim": return "eSIM"/);
  assert.doesNotMatch(deviceHome, /prompt:\s*item/);
  assert.match(deviceTransport, /if \(!allowedPath\(path\)\)/);
  assert.match(deviceTransport, /setInstanceFollowRedirects\(false\)/);
  assert.match(deviceTransport, /DEVICE_HOME_RESPONSE_TOO_LARGE/);
  assert.match(deviceTransport, /taskDetailPath\(String kind, String id\)/);
  assert.match(deviceTransport, /DEVICE_HOME_TASK_REFERENCE_REJECTED/);
  assert.match(shellApi, /const int API_VERSION = 18/);
  assert.match(shellApi, /String claimRockstarServiceEntitlement\(String packageJson\)/);
  assert.match(shellApi, /String cloudA2AAgents\(\)/);
  assert.match(shellApi, /String requestCloudA2APriceQuote\(/);
  assert.match(shellApi, /String prepareCloudA2ADelegation\(String draftJson\)/);
  assert.match(shellApi, /String recoverCloudA2ADelegation\(String parentJobId, String idempotencyKey, String inputSha256\)/);
  assert.match(shellApi, /String requestCloudA2AWalletReservation\(String draftJson\)/);
  assert.match(shellApi, /String confirmCloudA2AWalletReservation\(String draftJson, String approvalId\)/);
  assert.match(shellApi, /String releaseCloudA2AWalletReservation\(String delegationId\)/);
  assert.match(shellApi, /String registerCloudA2ABrokerAuthorization\(String draftJson\)/);
  assert.match(shellApi, /String approveCloudA2ADelegation\(String draftJson\)/);
  assert.match(shellApi, /String recoverCloudA2AExecution\(String draftJson\)/);
  assert.match(shellApi, /String cancelCloudA2ADelegation\(String delegationId\)/);
  assert.match(shellUi, /見積を確認/);
  assert.match(shellUi, /見積取得は依頼文をProviderへ共有しますが、有料実行は行いません/);
  assert.match(shellUi, /!response\.optBoolean\("verified"\)/);
  assert.match(shellService, /new A2AUsageReceiptVerifier\.PriceQuoteIntent\(/);
  assert.match(shellService, /requestA2APriceQuote\(authorization, agentId/);
  assert.match(a2aJson, /UNSUPPORTED_A2A_JSON_VALUE/);
  assert.match(shellApi, /String enrollA2ABrokerDevice\(boolean requireStrongBox\)/);
  assert.match(shellApi, /String revokeA2ABrokerDevice\(String keyId\)/);
  assert.match(shellApi, /String syncA2AWalletSettlement\(String delegationId\)/);
  assert.match(shellConnection, /static final int API_VERSION = 18/);
  assert.match(shellConnection, /api\.claimRockstarServiceEntitlement\(packageJson\)/);
  assert.match(shellUi, /claimRedemptionAvailable/);
  assert.match(shellUi, /setSaveEnabled\(false\)/);
  assert.match(shellUi, /claimRockstarServiceEntitlement\(packageJson\)/);
  assert.match(deviceTransport, /claimRockstarServiceEntitlement\(String authorization, String packageJson\)/);
  assert.ok(deviceTransport.includes('packageBytes.length > 16_384'));
  assert.ok(deviceTransport.includes('envelope.length() != 2'));
  assert.ok(deviceTransport.includes('allowedPostPath(path)'));
  assert.ok(deviceTransport.includes('DEVICE_HOME_NETWORK_ON_MAIN_THREAD'));
  assert.ok(deviceTransport.includes('Arrays.fill(packageBytes, (byte) 0)'));
  assert.match(deviceTransport, /"\/api\/rockstar\/entitlements"/);
  assert.match(shellService, /claimRockstarServiceEntitlement\(String packageJson\)/);
  assert.match(shellService, /deviceSessionStore\(\)\.authorizationHeader\(\)/);
  assert.ok(shellUi.includes('setPositiveButton("このIDに登録"'));
  assert.ok(shellUi.includes('自動再送はしていません'));
  assert.match(shellConnection, /api\.prepareCloudA2ADelegation\(draftJson\)/);
  assert.match(shellConnection, /api\.recoverCloudA2ADelegation\(parentJobId, idempotencyKey, inputSha256\)/);
  assert.match(shellConnection, /api\.requestCloudA2AWalletReservation\(draftJson\)/);
  assert.match(shellConnection, /api\.confirmCloudA2AWalletReservation\(draftJson, approvalId\)/);
  assert.match(shellConnection, /api\.releaseCloudA2AWalletReservation\(delegationId\)/);
  assert.match(shellConnection, /api\.registerCloudA2ABrokerAuthorization\(draftJson\)/);
  assert.match(shellConnection, /api\.approveCloudA2ADelegation\(draftJson\)/);
  assert.match(shellConnection, /api\.recoverCloudA2AExecution\(draftJson\)/);
  assert.match(shellConnection, /api\.cancelCloudA2ADelegation\(delegationId\)/);
  assert.match(shellUi, /cloudA2aExecutionConsent\.isChecked\(\)/);
  assert.match(shellService, /requireHeldQuoteBoundA2ABudget\(draft\.hold, now\)/);
  assert.match(shellService, /recoveredByReadback/);
  assert.match(delegationReadApi, /brokerAuthorization: brokerAuthorization \? \{/);
  assert.match(delegationReadApi, /registered: true/);
  assert.doesNotMatch(delegationReadApi, /proofJson/);
  assert.match(shellUi, /Cloudに一致する委任案/);
  assert.match(shellUi, /親job全体で許可する最大額/);
  assert.match(shellUi, /再送せず、保存状態を照合/);
  assert.match(shellUi, /この上限でCloud作業を承認/);
  assert.match(shellUi, /同じ委任IDの状態を読み取り確認/);
  assert.match(shellService, /reconcileA2ABudgetDispatched\(owner, id, cloudState, now\)/);
  assert.match(shellService, /findA2AWalletReservation\(owner, id\)/);
  assert.match(shellService, /A2ARecoveryBinding\.matches\(cloudA2ARecoveryTerms\(delegation, quote\), local\)/);
  assert.match(recoveryBinding, /MessageDigest\.isEqual/);
  assert.match(recoveryBinding, /RECOVERABLE_WALLET_STATES/);
  assert.match(recoveryBindingTest, /missingLocalReservationCannotRecover/);
  assert.match(recoveryBindingTest, /foreignOwnerCannotRecoverAnotherOwnersReservation/);
  assert.match(recoveryBindingTest, /changedParentAgentOrWalletApprovalDigestCannotRecover/);
  assert.match(shellService, /PlatformStore\.a2aBudgetPayloadDigest\(hold\)/);
  assert.match(recoveryBindingTest, /changedPriceCurrencyCapDeadlineOrQuoteTimeCannotRecover/);
  assert.match(recoveryBindingTest, /onlyActiveWalletReservationStatesCanRecover/);
  assert.match(shellUi, /同じ委任IDのCloud・端末Wallet状態を照合/);
  assert.match(shellUi, /releaseRecoveredA2ABudget\(delegationId\)/);
  assert.match(shellService, /fenceA2ABudgetForUnknownDispatch/);
  assert.match(brokerEnrollment, /reconcileA2ABudgetDispatched\(owner, delegationId/);
  assert.match(shellService, /authorizationSha256\(intent\)/);
  assert.match(shellService, /recoveryRequired/);
  assert.match(shellConnection, /api\.enrollA2ABrokerDevice\(requireStrongBox\)/);
  assert.match(shellConnection, /api\.revokeA2ABrokerDevice\(keyId\)/);
  assert.match(shellConnection, /api\.syncA2AWalletSettlement\(delegationId\)/);
  assert.match(brokerEnrollment, /A2ABrokerDeviceKeyStore\.provision\(\s*context, challengeBytes, requireStrongBox\)/);
  assert.match(brokerEnrollment, /transport\.register\(authorization, challengeId, nonce, chain\)/);
  assert.match(brokerEnrollment, /A2ABrokerDeviceKeyStore\.retire\(context, requestedKeyId\)/);
  assert.match(brokerEnrollment, /platform\.a2aWalletReservation\(owner, delegationId\)/);
  assert.match(brokerEnrollment, /new A2AWalletSettlementSync\(platform, source\)/);
  assert.match(brokerTransport, /setInstanceFollowRedirects\(false\)/);
  assert.match(brokerTransport, /setUseCaches\(false\)/);
  assert.match(brokerTransport, /Authorization", authorization/);
  assert.match(brokerKeyStore, /A2A_BROKER_KEY_NOT_HARDWARE_BACKED/);
  assert.match(brokerKeyStore, /setAttestationChallenge\(challenge\.clone\(\)\)/);
  assert.match(shellService, /PROVIDER_USAGE_TRUST_UNCONFIGURED/);
  assert.match(shellUi, /このBroker端末をattestation登録/);
  assert.match(shellUi, /サーバーの鍵を失効中/);
  assert.match(shellUi, /server_revoked_local_cleanup_pending/);
  assert.match(brokerEnrollment, /server_revoked_local_cleanup_pending/);
  assert.match(shellUi, /既存のWallet受取を同期/);
  assert.match(shellApi, /String cloudServiceHome\(\)/);
  assert.match(shellApi, /String cloudTaskDetail\(String kind, String taskId\)/);
  assert.match(shellApi, /String prepareCloudLlmQuote\(String requestId, String prompt, long maximumBudgetMinor, String currency, boolean saveResult\)/);
  assert.match(shellApi, /String executeCloudLlmQuote\(String prompt, String quoteId, String approvalDigest, String model, int outputTokenLimit\)/);
  assert.match(shellUi, /クラウドの状態・作業結果を更新/);
  assert.match(shellUi, /LLM明細・保存成果を開く/);
  assert.match(shellUi, /成果を取得/);
  assert.match(shellUi, /料金を見積もって依頼を準備/);
  assert.match(shellUi, /最大額（通貨単位）/);
  assert.match(shellUi, /UsageCurrencyFormatter\.formatMinor/);
  assert.match(shellUi, /UsageCurrencyFormatter\.formatRatePerMillionTokens/);
  assert.match(shellCurrencyFormatter, /Currency\.getInstance\(currencyCode\)\.getDefaultFractionDigits\(\)/);
  assert.match(shellCurrencyFormatter, /parseMajorToMinor/);
  assert.match(shellCurrencyFormatter, /movePointLeft\(6 \+ digits\)/);
  assert.match(shellUi, /Long parsedCap = UsageCurrencyFormatter\.parseMajorToMinor\(cloudLlmBudget\.getText\(\)\.toString\(\), currency\)/);
  assert.doesNotMatch(shellUi, /Long\.parseLong\(capText\)/);
  assert.match(shellUi, /単価（各100万token当たり/);
  assert.match(shellUi, /実行中の暫定見積/);
  assert.match(shellUi, /Provider確定meterではありません/);
  assert.match(shellUi, /実行中のProvider使用額は未報告/);
  assert.match(shellUi, /llmQueueLabel\(item\.optString\("queueState"/);
  assert.match(shellUi, /formatCloudTaskDetail\(kind, parsed\)/);
  assert.match(shellUi, /appendProviderUsageLines\(text, live\.optJSONObject\("snapshot"\), currency, amount\)/);
  assert.match(shellUi, /appendRemoteAiUsageLines\(text, price/);
  assert.match(shellUi, /最近の進捗/);
  assert.match(shellUi, /cloudTaskHandler\.postDelayed\(cloudTaskRefresh, delay\)/);
  assert.match(shellUi, /cloudTaskHandler\.removeCallbacks\(cloudTaskRefresh\)/);
  assert.match(shellUi, /isCloudWorkActive\(item\.optString\("remoteState"/);
  assert.match(shellUi, /停止要求をCloudへ一度送ります/);
  assert.match(shellUi, /相手Agentの停止はまだ確認できていません/);
  assert.match(shellService, /cancelA2ADelegation\(authorization, delegationId\)/);
  assert.match(shellService, /cancel_unconfirmed/);
  assert.match(shellUi, /実行中の暫定使用額/);
  assert.match(shellUi, /保存されたAgent成果/);
  assert.match(shellUi, /表示された上限額を承認/);
  assert.match(shellUi, /executeCloudLlmQuote/);
  assert.match(automationGradle, /a2aProviderUsageKeysJson.*getOrElse\('\[\]'\)/);
  assert.match(automationGradle, /A2A_PROVIDER_USAGE_KEYS_JSON/);
  assert.match(usageTrustConfig, /Set\.of\(\s*"providerId", "keyId", "agentOrigin", "publicKeyBase64", "revoked"/);
  assert.match(usageTrustConfig, /NON_CANONICAL_A2A_PROVIDER_USAGE_KEY/);
  assert.match(usageTrustConfig, /new A2AUsageReceiptVerifier\(keys\)/);
  assert.match(rockApplication, /AndroidA2AUsageTrustConfig\.verifier\(/);
  assert.match(rockApplication, /receiptVerifier\.hasTrustedKeys\(\)/);
  assert.match(rockApplication, /a2aProviderUsageTrustConfigurationValid = false/);
  assert.match(rockApplication, /new A2AUsageReceiptVerifier\(List\.of\(\)\)/);
  assert.match(shellService, /PROVIDER_USAGE_TRUST_INVALID/);
  assert.match(shellService, /application\.a2aProviderUsageTrustConfigured\(\)/);
  assert.match(shellService, /PROVIDER_USAGE_TRUST_UNCONFIGURED/);
});

void test('native A2A Wallet hold, Broker proof, and Cloud approval stay ordered and one-shot', () => {
  const service = read('android/automation/src/main/java/dev/rock/automation/RockShellService.java');
  const method = (start, end) => {
    const from = service.indexOf(start);
    const to = service.indexOf(end, from + start.length);
    assert.ok(from >= 0 && to > from, `missing source boundary: ${start}`);
    return service.slice(from, to);
  };
  const requestHold = method(
    '@Override public String requestCloudA2AWalletReservation(String draftJson)',
    '@Override public String confirmCloudA2AWalletReservation',
  );
  const confirmHold = method(
    '@Override public String confirmCloudA2AWalletReservation',
    '@Override public String releaseCloudA2AWalletReservation',
  );
  const registerProof = method(
    '@Override public String registerCloudA2ABrokerAuthorization',
    '@Override public String approveCloudA2ADelegation',
  );
  const approveCloud = method(
    '@Override public String approveCloudA2ADelegation',
    '@Override public String recoverCloudA2AExecution',
  );
  const verifyDraft = method(
    'private VerifiedA2ADraft verifyCloudA2ADraft(String draftJson)',
    'private static String a2aWalletApprovalContext',
  );

  assert.match(verifyDraft, /remote\.optString\("state"\)\)/);
  assert.match(verifyDraft, /verifyA2AQuote\(remoteQuote, origin, name, version, message, currency, cap\)/);
  assert.match(verifyDraft, /new A2AUsageReceiptVerifier\.Hold\(owner, parentJobId,\s*id, id,/);
  assert.match(requestHold, /proposeA2AWalletApproval/);
  assert.match(requestHold, /new Intent\(RockShellService\.this, ApprovalActivity\.class\)/);
  assert.doesNotMatch(requestHold, /reserveA2ABudget|approveA2ADelegation/);
  assert.match(confirmHold, /PlatformStore\.a2aBudgetPayloadDigest\(draft\.hold\)/);
  assert.match(confirmHold, /"ISSUED"\.equals\(approval\.get\("state"\)\)/);
  assert.match(confirmHold, /platform\.reserveA2ABudget\(approvalId/);
  assert.match(confirmHold, /response\.put\("executionStarted", false\)/);
  assert.match(registerProof, /requireHeldQuoteBoundA2ABudget\(draft\.hold, now\)/);
  assert.match(registerProof, /authorizeHeldDelegation\(/);
  assert.match(registerProof, /transport\.registerA2ABrokerAuthorization\(/);
  assert.match(approveCloud, /requireHeldQuoteBoundA2ABudget\(draft\.hold, now\)/);
  assert.match(approveCloud, /proof\.optBoolean\("registered"\)/);
  assert.match(approveCloud, /transport\.approveA2ADelegation\(/);
  assert.match(approveCloud, /catch \(java\.io\.IOException uncertain\)/);
  assert.match(approveCloud, /fenceUnknownCloudA2AApproval/);
});
