'use strict';
const $ = s => document.querySelector(s);
const el = (tag, cls, text) => {const n=document.createElement(tag); if(cls)n.className=cls; if(text!==undefined)n.textContent=text;return n};
const moneyFormat = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const money = n => moneyFormat.format(n/100);
let renderedWallet=null,walletMutationPending=false;
let state={hub:{installed:[],jobs:[]},wallet:{}},catalog=[],view='hub',selected=null,toastTimer,lastFocus;
const labels={hub:'Automation Hub',installed:'マイツール',history:'実行履歴',wallet:'Rock Wallet',developer:'Developer SDK',device:'端末と実行環境'};
function notice(text){$('#toast').textContent=text;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),5500)}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'処理できませんでした');return data}
// A navigation shares in-flight reads. Mutations invalidate the epoch so a
// response started before the mutation can never overwrite its newer state.
const resources={state:{path:'/api/state',ttl:1000,epoch:0,loaded:-1,at:0},catalog:{path:'/api/catalog',ttl:30000,epoch:0,loaded:-1,at:0}};
async function loadResource(resource){
  if(!resource.flight&&resource.loaded===resource.epoch&&performance.now()-resource.at<resource.ttl)return resource.value;
  if(!resource.flight){
    const epoch=resource.epoch;
    resource.flight=api(resource.path).then(value=>{if(epoch===resource.epoch){resource.value=value;resource.loaded=epoch;resource.at=performance.now();resource.wallAt=Date.now();resource.error=null}}).catch(error=>{if(epoch===resource.epoch)resource.error=error.message;throw error}).finally(()=>{resource.flight=null;if(resource===resources.state)renderWalletStatus()});
    if(resource===resources.state)renderWalletStatus();
  }
  await resource.flight;
  return resource.loaded===resource.epoch?resource.value:loadResource(resource);
}
async function refresh({forceState=false,reloadCatalog=false}={}){
  if(forceState)resources.state.epoch++;
  if(reloadCatalog)resources.catalog.epoch++;
  const pending=[loadResource(resources.state).then(value=>{if(resources.state.loaded!==resources.state.epoch||value!==resources.state.value)return;state=value;$('#installed-count').textContent=state.hub.installed.length;render()})];
  if(view==='hub'||view==='installed'||reloadCatalog)pending.push(loadResource(resources.catalog).then(value=>{if(resources.catalog.loaded!==resources.catalog.epoch||value!==resources.catalog.value)return;catalog=value.packages;render()}));
  await Promise.all(pending);
}
async function action(path,body,message){const wallet=path.startsWith('/api/wallet/');if(wallet&&!walletCurrent())throw new Error('Walletの最新状態を取得してから操作してください');if(wallet){walletMutationPending=true;renderWalletStatus()}try{const data=await api(path,body);await refresh({forceState:true});if(message)notice(message);return data.result}catch(error){if(wallet)resources.state.error=error.message;notice(error.message);throw error}finally{if(wallet){walletMutationPending=false;renderWalletStatus()}}}
function button(text,cls,fn){const b=el('button',cls,text);b.addEventListener('click',async()=>{b.disabled=true;try{await fn()}catch(e){if(e.message)notice(e.message)}finally{b.disabled=false;if(view==='wallet')renderWalletStatus()}});return b}
function showView(name){if(!Object.hasOwn(labels,name))return;view=name;document.querySelectorAll('.view').forEach(n=>n.classList.toggle('hidden',n.id!=='view-'+name));document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===name));$('#crumb').textContent=labels[name];render();if(['hub','installed','history','wallet'].includes(name))refresh({forceState:name==='wallet'}).catch(e=>notice(e.message))}
document.querySelectorAll('[data-view]').forEach(n=>n.addEventListener('click',()=>showView(n.dataset.view)));
$('#refresh-catalog').addEventListener('click',async event=>{const control=event.currentTarget;control.disabled=true;try{await refresh({reloadCatalog:true});notice('ストアの一覧を更新しました')}catch(error){notice(error.message)}finally{control.disabled=false}});
$('#refresh-wallet').addEventListener('click',()=>refresh({forceState:true}).catch(error=>notice(error.message)));
$('#search').addEventListener('input',renderCatalog);
document.querySelectorAll('[data-filter]').forEach(n=>n.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===n));renderCatalog()}));
function groups(){const g=new Map();for(const p of catalog){const id=p.manifest.id;if(!g.has(id))g.set(id,[]);g.get(id).push(p)}for(const versions of g.values())versions.sort((a,b)=>{const av=a.manifest.version.split('.').map(Number),bv=b.manifest.version.split('.').map(Number);return av[0]-bv[0]||av[1]-bv[1]||av[2]-bv[2]});return g}
function installed(id){return state.hub.installed.find(x=>x.id===id)}
function card(p,versions){const m=p.manifest,i=installed(m.id),node=el('article','tool-card');const top=el('div','card-top');top.append(el('div','tool-icon'+(m.id.includes('list')?' purple':''),m.id.includes('list')?'≡':'Aa'),el('span','tag',i?(i.enabled?'有効化済み':'承認待ち'):'このPC内で実行'));node.append(top,el('h3','',m.name),el('p','',m.description),el('div','publisher','Rock development · v'+(i?i.version:m.version)));const bottom=el('div','card-bottom'),price=el('div','price','無料');price.append(el('small','','外部送信なし'));const open=button(i?'ツールを開く ↗':'詳細を見る →',i?'secondary':'primary',()=>openTool(m.id));open.dataset.toolId=m.id;bottom.append(price,open);node.append(bottom);if(versions.length>1&&!i)node.append(el('small','publisher','v2への更新も試せます'));return node}
function renderCatalog(){const root=$('#catalog');root.replaceChildren();const search=$('#search').value.trim().toLowerCase();for(const [id,versions]of groups()){const p=versions[0];if((p.manifest.name+' '+p.manifest.description+' '+id).toLowerCase().includes(search))root.append(card(p,versions))}if(!root.children.length)root.append(el('div','empty','一致するツールがありません。'))}
function renderInstalled(){const root=$('#installed-list');root.replaceChildren();for(const i of state.hub.installed){const versions=groups().get(i.id)||[];root.append(card({manifest:i.manifest},versions))}if(!root.children.length)root.append(el('div','empty','ツールをダウンロードすると、ここに表示されます。'))}
function saveFile(name,text,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const statusLabel={running:'実行中',succeeded:'完了',failed:'失敗',cancelled:'キャンセル済み',interrupted:'再起動で中断'};
function renderHistory(){const root=$('#history-list');root.replaceChildren();for(const job of state.hub.jobs){const row=el('article','receipt'),head=el('div','receipt-header');head.append(el('strong','',job.tool_id),el('span','tag',statusLabel[job.status]||job.status));row.append(head,el('small','',new Date(job.created*1000).toLocaleString('ja-JP')+' · v'+job.version+' · このPC · $0.00'),el('small','','PACKAGE '+job.package_hash));if(job.output!==null)row.append(el('pre','',job.output));if(job.error)row.append(el('p','warning',job.error));const actions=el('div','action-row');if(job.output!==null)actions.append(button('結果を保存 ↓','secondary',()=>saveFile('rock-result.txt',job.output)));actions.append(button('実行記録を保存 ↓','secondary',()=>saveFile('rock-receipt.json',JSON.stringify(job,null,2),'application/json')));if(job.status==='running')actions.append(button('キャンセル','danger',()=>action('/api/cancel',{id:job.id},'キャンセルしました')));row.append(actions);root.append(row)}if(!root.children.length)root.append(el('div','empty','ツールを実行すると、結果と記録がここに保存されます。'))}
function closeTool(){const id=selected;$('#drawer').classList.add('hidden');$('#drawer-backdrop').classList.add('hidden');document.body.style.overflow='';selected=null;const visible=n=>n?.isConnected&&n.getClientRects().length;const trigger=id?document.querySelector('[data-tool-id=\"'+CSS.escape(id)+'\"]'):null;const heading=document.querySelector('#view-'+view+' h1');if(visible(lastFocus))lastFocus.focus();else if(visible(trigger))trigger.focus();else if(heading){heading.tabIndex=-1;heading.focus()}}
$('#close-drawer').addEventListener('click',closeTool);$('#drawer-backdrop').addEventListener('click',closeTool);
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeTool();if(e.key==='Tab'&&!$('#drawer').classList.contains('hidden')){const focusable=[...$('#drawer').querySelectorAll('button:not(:disabled),input,textarea,select')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
function fact(dl,name,value){dl.append(el('dt','',name),el('dd','',value))}
async function download(p){const packageBody=await api(p.download);await action('/api/install',{package:packageBody},'署名を検証し、インストールしました。権限の承認で有効になります。')}
function openTool(id,version){const current=installed(id),versions=groups().get(id)||[],p=versions.find(x=>x.manifest.version===(version||current?.version))||versions[0]||{manifest:current.manifest,hash:current.hash};if(!p)return;if($('#drawer').classList.contains('hidden'))lastFocus=document.activeElement;selected=id;$('#drawer').classList.remove('hidden');$('#drawer-backdrop').classList.remove('hidden');document.body.style.overflow='hidden';const root=$('#drawer-content');root.replaceChildren();const m=p.manifest;root.append(el('div','tool-icon'+(id.includes('list')?' purple':''),id.includes('list')?'≡':'Aa'));const title=el('h2','',m.name);title.id='drawer-title';root.append(title,el('p','',m.description));const facts=el('dl','facts');fact(facts,'実行場所','このPC（ホスト試作）');fact(facts,'利用するデータ','この画面に入力した文章のみ');fact(facts,'外部送信','なし');fact(facts,'権限','文章の入力・結果の出力');fact(facts,'料金','無料 / $0.00');fact(facts,'上限','入力64 KiB・出力128 KiB・3秒');fact(facts,'作者',m.publisher+'（開発用）');fact(facts,'パッケージ',Math.ceil((p.size||0)/1024)+' KiB · Ed25519 テスト署名');root.append(facts);
const select=el('select');select.setAttribute('aria-label','バージョン');for(const v of versions){const o=el('option','','バージョン '+v.manifest.version+(current?.version===v.manifest.version?'（導入済み）':''));o.value=v.manifest.version;o.selected=v.manifest.version===m.version;select.append(o)}select.addEventListener('change',()=>openTool(id,select.value));if(versions.length)root.append(select);
if(!current||current.version!==m.version){const actions=el('div','action-row');actions.append(button(current?'この版をダウンロードして更新 ↓':'ダウンロードしてインストール ↓','primary',async()=>{await download(p);openTool(id,m.version)}));if(current?.cached_versions.includes(m.version))actions.append(button('保存済みの版へ復元','secondary',async()=>{await action('/api/lifecycle',{id,action:'rollback',version:m.version},'旧版へ復元しました。再承認して利用できます。');openTool(id,m.version)}));root.append(actions)}else if(!current.enabled){const check=el('label','check'),checkbox=el('input');checkbox.type='checkbox';checkbox.id='approve-tool';check.append(checkbox,el('span','','上の実行場所・データ・権限・料金を確認し、このバージョンを有効にします。'));const enable=button('承認して有効にする','primary',async()=>{await action('/api/enable',{id,approved_hash:current.hash},'ツールを有効にしました');openTool(id,m.version)});enable.disabled=true;checkbox.addEventListener('change',()=>enable.disabled=!checkbox.checked);root.append(check,enable)}else{const label=el('label','field','処理する文章');label.htmlFor='tool-input';const input=el('textarea');input.id='tool-input';input.placeholder='ここに文章を入力してください';input.value=id.includes('list')?'りんご\nみかん\nりんご\n  ぶどう  ':'  今日のメモ  \n\n\n  ひとつずつ、作業を進める。  ';root.append(label,input);const actions=el('div','action-row');actions.append(button('このPCで実行 →','primary',async()=>{const result=await action('/api/run',{id,text:input.value,key:crypto.randomUUID(),target:'device_local'},'実行を開始しました');const output=el('div');output.id='live-result';$('#live-result')?.remove();root.append(output);for(let n=0;n<30;n++){await new Promise(resolve=>setTimeout(resolve,200));await refresh();const job=state.hub.jobs.find(j=>j.id===result.id);if(job?.status!=='running'){output.replaceChildren(el('div','result-label',statusLabel[job.status]||job.status),el('pre','panel',job.output??job.error??''));if(job.output!==null)output.append(button('結果を保存 ↓','secondary',()=>saveFile('rock-result.txt',job.output)));break}}}),button('実行履歴を見る','secondary',()=>{closeTool();showView('history')}));root.append(actions)}
if(current){const actions=el('div','action-row');if(current.enabled)actions.append(button('停止する','secondary',async()=>{await action('/api/lifecycle',{id,action:'disable'},'停止しました');openTool(id,m.version)}));actions.append(button('削除する','danger',async()=>{await action('/api/lifecycle',{id,action:'uninstall'},'ツールを削除しました。実行記録は残ります。');closeTool()}));root.append(actions)}root.append(el('p','','結果と実行記録はこのPCに保存されます。入力は実行後に保持せず、結果は削除後も履歴に残します。'));$('#close-drawer').focus()}
function walletCurrent(){const r=resources.state;return r.loaded===r.epoch&&!r.error&&!r.flight&&!walletMutationPending&&performance.now()-r.at<15000}
function renderWalletStatus(){if(view!=='wallet')return;const r=resources.state,node=$('#wallet-sync'),fresh=walletCurrent();const time=r.wallAt?new Date(r.wallAt).toLocaleTimeString('ja-JP'):'';node.textContent=r.loaded<0?'Walletの状態を取得しています…':walletMutationPending?'操作の結果を確認しています…':r.flight?'保存した情報を表示しています。更新中…':fresh?'最終取得 '+time+' · 現在のテスト台帳を表示':(r.error?'更新できませんでした。':'保存した情報です。')+' 最終取得 '+time+'。状態を更新してから操作してください。';node.classList.toggle('sync-stale',!fresh);$('#wallet-content').querySelectorAll('[data-wallet-mutation]').forEach(control=>control.disabled=!fresh);$('#refresh-wallet').disabled=!!r.flight||walletMutationPending}
function walletPanel(title){const p=el('div','panel');p.append(el('h2','',title));return p}
function renderWallet(){const w=state.wallet,root=$('#wallet-content'),fingerprint=JSON.stringify(w);if(renderedWallet===fingerprint&&root.children.length){const consent=root.querySelector('#wallet-consent');if(consent)consent.checked=w.consent?.accepted===true||w.consent?.accepted===1;renderWalletStatus();return}renderedWallet=fingerprint;root.replaceChildren();const amounts=el('div','money-grid');for(const [label,n]of [['利用可能（テスト）',w.available_minor],['精算待ち',w.pending_minor],['出金保留',w.held_minor]]){const p=el('div','panel');p.append(el('div','money-label',label),el('div','money',money(n||0)));amounts.append(p)}root.append(amounts);const controls=el('div','wallet-actions');let p=walletPanel('売上と精算');p.append(el('p','','売上を登録すると精算待ちへ。精算完了後に利用可能額へ移ります。'));p.append(button('テスト売上 $50 を登録','primary',()=>action('/api/wallet/sale',{amount_minor:5000,key:crypto.randomUUID()},'テスト売上を登録しました')));for(const sale of w.sales||[]){const row=el('div','transaction'),t=el('div','',money(sale.amount_minor));t.append(el('small','',sale.status));row.append(t);if(sale.status==='PENDING_SETTLEMENT')row.append(button('精算を完了','secondary',()=>action('/api/wallet/settle',{id:sale.id,key:crypto.randomUUID()},'精算済み残高へ移しました')));p.append(row)}controls.append(p);
p=walletPanel('月額 $8.88 の引落し試験');p.append(el('p','','精算済みUSDから月ごとに1回、888セント。同じ月に再実行しても重複しません。追加料金・不足時の部分徴収はありません。'));const accepted=w.consent?.accepted===true||w.consent?.accepted===1;const check=el('label','check'),box=el('input');box.type='checkbox';box.id='wallet-consent';box.checked=accepted;check.append(box,el('span','','月額$8.88、Walletからの継続引落しにテスト同意します。撤回すると次の試験請求を拒否します。'));box.addEventListener('change',()=>action('/api/wallet/consent',{accepted:box.checked},'同意の控えを保存しました').catch(()=>{}));p.append(check);const period=el('input');period.type='month';period.value=new Date().toISOString().slice(0,7);period.setAttribute('aria-label','試験する請求月');const row=el('div','action-row');row.append(period,button('この月を請求','secondary',()=>action('/api/wallet/bill',{period:period.value,key:crypto.randomUUID()},'請求結果を台帳へ反映しました')));p.append(row,el('p','','実サービスの自動引落しは未接続です。このボタンはbackend請求処理の手動試験です。'));controls.append(p);
p=walletPanel('ATMの排出・復旧試験');p.append(el('p','','$20を予約し、部分排出や結果不明を再現します。確認が済むまで未排出分を保留します。'));p.append(button('$20の出金を予約','primary',()=>action('/api/wallet/reserve',{amount_minor:2000,key:crypto.randomUUID()},'テスト出金を予約しました')));for(const wd of w.withdrawals||[]){const row=el('div','transaction'),info=el('div','',money(wd.amount_minor)+' / 排出済み '+money(wd.dispensed_minor));info.append(el('small','',wd.status));row.append(info);p.append(row);if(!['DISPENSED','REVERSED','PARTIAL_REVERSED'].includes(wd.status)){const a=el('div','action-row');if(wd.dispensed_minor===0)a.append(button('$10だけ排出','secondary',()=>action('/api/wallet/dispense',{id:wd.id,dispensed_minor:1000,key:crypto.randomUUID()},'部分排出を記録しました。残額は保留中です。')));a.append(button('結果不明を再現','secondary',()=>action('/api/wallet/unknown',{id:wd.id},'結果不明として保留を維持しました')),button('照合して残額を返還','secondary',()=>action('/api/wallet/reconcile',{id:wd.id,total_dispensed_minor:wd.dispensed_minor,key:crypto.randomUUID()},'確認済み排出額と照合し、未排出額を返還しました')));p.append(a)}}controls.append(p);
p=walletPanel('台帳と記録');p.append(el('p','','通貨：USD / 仕訳の差額：'+money(w.ledger_balance_minor||0)),el('p','','月額引落し累計：'+money(w.billed_minor||0)+' / 排出記録：'+money(w.dispensed_minor||0)),button('台帳・同意の控えを保存 ↓','secondary',()=>saveFile('rock-wallet-simulator.json',JSON.stringify(w,null,2),'application/json')),el('p','','単一利用者のシミュレーションです。本人確認と購入資格はテストデータ。passkey認証、銀行、実ATM、税務・規制対応は未実装です。'));controls.append(p);root.append(controls);root.querySelectorAll('button,input[type="checkbox"]').forEach(control=>{if(!control.textContent.includes('台帳・同意の控え'))control.dataset.walletMutation='true'});renderWalletStatus()}
function render(){if(view==='hub')renderCatalog();else if(view==='installed')renderInstalled();else if(view==='history')renderHistory();else if(view==='wallet'){if(resources.state.loaded<0){$('#wallet-content').replaceChildren(el('div','empty','Walletの状態を取得しています…'));return}renderWallet()}}
refresh().catch(e=>notice(e.message));
setInterval(()=>{if(view==='wallet'){renderWalletStatus();if(!resources.state.error&&!resources.state.flight&&!walletMutationPending&&performance.now()-resources.state.at>=10000)refresh({forceState:true}).catch(()=>{})}else if(state.hub.jobs.some(j=>j.status==='running'))refresh({forceState:true}).catch(()=>{})},1200);
