pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories { google(); mavenCentral() }
}
rootProject.name = 'RockStarOS'
include ':core', ':tool-sdk', ':local-ai-api', ':shell-api', ':automation', ':shell', ':article-tool'
