export type Automation = {
  id: string; name: string; category: string; description: string;
  source: string; license: string; licenseUrl: string; color: string;
  status: 'ready' | 'candidate' | 'pending'; runner?: 'coconala' | 'citations' | 'free-article' | 'delivery-local'; origin?: 'mr'; environment: string; cost: string;
  steps: string[]; note: string;
};
export const catalog: Automation[] = [
  {"id": "coconala", "name": "ココナラ案件チェック", "category": "案件・納品支援", "description": "依頼文と提案文から、面談の必要性や役割の食い違いを確認。応募前の判断を助けます。", "source": "https://github.com/k999ln/Mr./blob/26a39d2c31ea5246cb78dbe42d86e333922db60c/skills/earn/gig/scripts/application_eligibility.py", "runner": "coconala", "environment": "ブラウザ内 / Rockへのサインインが必要", "cost": "外部APIは使いません。サイト読込以外の追加通信はありません。", "steps": ["依頼文と送信前の提案文を用意する", "契約形態と発注率を元ページで確認する", "案件チェックを実行し、理由を確認する", "元ページの条件・規約を本人が確認して判断する"], "note": "Mr.の単発・非同期案件向けルールを移植しました。ココナラの規約や受注可否を保証せず、自動応募・返信・入金確認は行いません。", "color": "green", "license": "MIT", "licenseUrl": "/toolkits/mr-LICENSE.txt", "status": "ready", "origin": "mr"},
  {"id": "mr-free-article", "name": "記事の無料版メーカー", "category": "記事制作", "description": "完全版の原稿から無料の紹介記事を作成。要点と出典を残し、noteへの案内を添えます。", "source": "https://github.com/k999ln/Mr./blob/26a39d2c31ea5246cb78dbe42d86e333922db60c/skills/writer-agent/scripts/_shared/make-free-version.py", "runner": "free-article", "environment": "ブラウザ内 / Rockへのサインインが必要", "cost": "外部AIや有料APIを使わず、端末内で文章を処理します。", "steps": ["自分が利用できる原稿を用意する", "無料にする範囲・まとめ・完全版のリンクを入力する", "作成結果と残したい有料部分を確認する", "必要な形式で保存し、本人が公開する"], "note": "まとめは入力した文章を使用します。記事の自動執筆・noteへの投稿・販売は行いません。", "color": "blue", "license": "MIT", "licenseUrl": "/toolkits/mr-LICENSE.txt", "status": "ready", "origin": "mr"},
  {"id": "mr-citations", "name": "出典整理ツール", "category": "記事制作", "description": "本文中の出典リンクを一覧に整理。同じURLをまとめ、コードや非リンクの出典は保ちます。", "source": "https://github.com/k999ln/Mr./blob/26a39d2c31ea5246cb78dbe42d86e333922db60c/skills/writer-agent/scripts/_shared/citation-strip.py", "runner": "citations", "environment": "ブラウザ内 / Rockへのサインインが必要", "cost": "端末内のテキスト処理のみ。外部APIや追加サービスは不要です。", "steps": ["出典リンクを含むMarkdownを貼り付ける", "出典整理を実行する", "本文と出典の対応を自分で確認する", "結果をコピーまたはMarkdownで保存する"], "note": "出典の事実確認は行いません。引用元との対応が必要な記事では、整理後の表記を確認してください。", "color": "orange", "license": "MIT", "licenseUrl": "/toolkits/mr-LICENSE.txt", "status": "ready", "origin": "mr"},
  {"id": "mr-delivery", "name": "納品記録の照合", "category": "案件・納品支援", "description": "契約条件・成果物・制作記録・レビューを照合。納品前の記録の不一致を見つけます。", "source": "https://github.com/k999ln/Mr./blob/26a39d2c31ea5246cb78dbe42d86e333922db60c/skills/earn/gig/scripts/deliverable_verifier.py", "runner": "delivery-local", "environment": "PC / Python 3.10以上", "cost": "PC内でファイルを読み照合します。追加の通信・API料金はありません。", "steps": ["無料パックを展開し、Python環境を用意する", "同梱サンプルで実行方法を確認する", "成果物・契約・制作記録・別レビューのデータを用意する", "照合結果を確認してから、本人が納品する"], "note": "内容の品質を自動判断するのではなく、別途作成したレビューとファイルを照合します。検出対象は限定的で、秘密情報の不在も保証しません。", "color": "pink", "license": "MIT", "licenseUrl": "/toolkits/mr-LICENSE.txt", "status": "ready", "origin": "mr"},
  {id:'faster-whisper',name:'faster-whisper',category:'文字起こし',description:'音声から、編集できるテキストへ。PCで使える文字起こしエンジン。',source:'https://github.com/SYSTRAN/faster-whisper',license:'MIT',licenseUrl:'https://github.com/SYSTRAN/faster-whisper/blob/master/LICENSE',color:'orange',status:'candidate',environment:'PC / Python。CPUまたは対応GPU',cost:'モデルの初回ダウンロードで通信量が増えます。実行中はPCの電力を使用。',steps:['公式READMEでOS・Python・ハードウェア要件を確認する','音声を扱う権限とモデルの利用条件を確認する','CodexでREADMEに沿ってローカル環境を準備する','短い音声で試し、誤変換を確認してから納品する'],note:'OSSの導入候補です。Rock starからの自動実行や収益連携は未対応です。'},
  {id:'transformers-js',name:'Transformers.js',category:'ブラウザAI',description:'ブラウザでモデルを実行。分類・要約などのワークフローの土台に。',source:'https://github.com/huggingface/transformers.js',license:'Apache-2.0',licenseUrl:'https://github.com/huggingface/transformers.js/blob/main/LICENSE',color:'blue',status:'candidate',environment:'対応ブラウザ / JavaScript・WebGPU等',cost:'モデルをダウンロードします。対応状況とメモリ・通信量はモデルごとに異なります。',steps:['公式READMEで対象タスクとブラウザ対応を確認する','使用モデルのカードとライセンスを個別に確認する','Codexで最小のサンプルを準備する','小さな入力で結果・処理時間・端末負荷を確認する'],note:'ライブラリのライセンスとモデルのライセンスは別です。モデルを自動配布・実行しません。'},
  {id:'playwright',name:'Playwright',category:'ブラウザ操作',description:'許可されたWeb操作を再現。確認作業や繰り返しのテストを効率化。',source:'https://github.com/microsoft/playwright',license:'Apache-2.0',licenseUrl:'https://github.com/microsoft/playwright/blob/main/LICENSE',color:'pink',status:'candidate',environment:'PC / Node.js・対応ブラウザ',cost:'ブラウザのダウンロードとページ読込で通信量が増えます。実行中はPCの電力を使用。',steps:['操作先の規約と自分の操作権限を確認する','公式READMEに沿ってCodexで環境を準備する','自分のテスト環境で操作を検証する','送信・購入等は本人が内容と実行を確認する'],note:'ココナラ等の第三者サイトの無人操作を許諾するものではありません。'}
];
