import test from 'node:test'; import assert from 'node:assert/strict';
import {evaluateCandidate,paperTransition,buildJevPayload,callerScore} from './index.mjs';
const strong=()=>({token:{symbol:'TEST',mint:'m',marketCapUsd:120000,liquidityUsd:45000,holders:450,top10Pct:18,devPct:1.2,bundlerPct:7,sniperPct:6,freshWalletPct:12,mintDisabled:true,freezeDisabled:true,volume1mUsd:25000,volume5mUsd:50000,volumeAcceleration:2.5,holderGrowthPct:18,liquidityGrowthPct:20},social:{mentions5m:160,mentionsPrev5m:60,uniqueAuthors5m:72,duplicateRatio:.05,referralRatio:.03,botRatio:.04,independentKolClusters:4,narrativeSimilarity:88,narrativePersistence:82},capital:{smartWalletBuyers:6,smartWalletSellers:0,verifiedWalletClusters:4,buyVolume1mUsd:18000,sellVolume1mUsd:4000},callers:[{id:'a',clusterId:'c1',verifiedWallet:true,walletBoughtBeforeCall:true,historicalHitRate:.65,medianMaxMultiple:4.2,postPumpCallRate:.05,deletedCallRate:.03},{id:'b',clusterId:'c2',verifiedWallet:true,walletBoughtBeforeCall:true,historicalHitRate:.58,medianMaxMultiple:3.7,postPumpCallRate:.08,deletedCallRate:.05},{id:'c',clusterId:'c3',verifiedWallet:true,walletBoughtBeforeCall:true,historicalHitRate:.61,medianMaxMultiple:5.1,postPumpCallRate:.04,deletedCallRate:.02}],risk:{suspiciousFundingClusterRatio:.05,honeypot:false,sellBlocked:false,ownerPrivileges:false}});
test('strong snapshot reaches ARMED/ENTER PAPER state',()=>{const r=evaluateCandidate(strong());assert.equal(r.mode,'PAPER_ONLY');assert.ok(['ARMED','ENTER'].includes(r.finalAction))});
test('honeypot blocks Jev ENTER',()=>{const x=strong();x.risk.honeypot=true;x.jevDecision={action:'ENTER'};assert.equal(evaluateCandidate(x).finalAction,'SKIP')});
test('spam lowers social quality',()=>{const a=evaluateCandidate(strong()),x=strong();x.social.duplicateRatio=.8;x.social.referralRatio=.7;x.social.botRatio=.6;const b=evaluateCandidate(x);assert.ok(b.social.organic<a.social.organic);assert.ok(b.consensus<a.consensus)});
test('caller integrity tracks verified independent clusters',()=>{const q=callerScore(strong().callers);assert.equal(q.verified,3);assert.equal(q.independent,3);assert.ok(q.score>=70)});
test('Jev payload cannot enable live',()=>{const x=strong(),e=evaluateCandidate(x),p=buildJevPayload(x,e);assert.equal(p.constraints.liveExecutionEnabled,false);assert.deepEqual(p.allowedActions,['SKIP','WATCH','ARMED','ENTER'])});
test('paper stages probe confirm scale and exits',()=>{const x=strong(),e={...evaluateCandidate(x),finalAction:'ENTER',exitRisk:10};const a=paperTransition(null,e,x),b=paperTransition(a,e,x),c=paperTransition(b,e,x);assert.equal(a.event,'PROBE');assert.equal(b.event,'CONFIRM');assert.equal(c.event,'SCALE');assert.equal(c.exposurePct,.1);const z=paperTransition(c,{...e,finalAction:'WATCH',exitRisk:90},x);assert.equal(z.event,'EXIT')});
