#!/bin/sh
set -eu
[ "${1:-start}" = start ] || exit 0
case " $(cat /proc/cmdline) " in
  *' rock.store.verify=1 '*) ;;
  *) exit 0 ;;
esac
exec /usr/bin/python3 -I -B /usr/lib/rock-platform/store-guest-test.py
