import { spawn } from 'node:child_process';
import {
  existsSync,
  openSync,
  fstatSync,
  readSync,
  closeSync,
  constants,
  lstatSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const header =
  '# Generated by scripts/amc-agent.mjs from data/amc/agent-definitions.json\n';
export function definitions() {
  const value = JSON.parse(
    readFileSync(join(root, 'data/amc/agent-definitions.json'), 'utf8'),
  );
  if (
    value.schema !== 'amc-agents/1' ||
    !Array.isArray(value.agents) ||
    value.agents.length !== 3
  )
    throw new Error('Invalid AMC agent definitions');
  const names = new Set();
  for (const agent of value.agents) {
    if (
      !/^[a-z][a-z-]+$/.test(agent.name) ||
      names.has(agent.name) ||
      !agent.description?.trim() ||
      !agent.developer_instructions?.trim()
    )
      throw new Error('Invalid AMC agent');
    if (
      Object.keys(agent).some(
        (k) =>
          ![
            'name',
            'description',
            'developer_instructions',
            'sandbox_mode',
          ].includes(k),
      )
    )
      throw new Error('Unexpected AMC agent setting');
    if (agent.sandbox_mode !== undefined && agent.sandbox_mode !== 'read-only')
      throw new Error('AMC agent cannot expand sandbox permissions');
    names.add(agent.name);
  }
  if (!['amc', 'amc-worker', 'amc-reviewer'].every((n) => names.has(n)))
    throw new Error('Missing AMC role');
  return value.agents;
}
export function renderAgent(agent) {
  // JSON basic strings are valid TOML strings for this controlled text registry.
  return (
    header +
    Object.entries(agent)
      .map(([k, v]) => `${k} = ${JSON.stringify(v)}`)
      .join('\n') +
    '\n'
  );
}
function regularDirectory(path) {
  if (
    existsSync(path) &&
    (!lstatSync(path).isDirectory() || lstatSync(path).isSymbolicLink())
  )
    throw new Error('Refusing unsafe agent directory: ' + path);
}
// Validate existing definitions without reopening a pathname after checking it.
// This is a read preflight; creation below still requires a trusted, stable parent.
function inspectExistingAgent(entry, config, directory) {
  const refuse = () => new Error(
    '既存のエージェント定義を保持します。差分を確認してください: ' + entry.path,
  );
  if (!Number.isInteger(constants.O_NOFOLLOW) || constants.O_NOFOLLOW <= 0 ||
      !Number.isInteger(constants.O_NONBLOCK) || constants.O_NONBLOCK <= 0)
    throw new Error('Safe agent definition reads are unavailable');
  let fd;
  try {
    fd = openSync(entry.path, constants.O_RDONLY | constants.O_NOFOLLOW | constants.O_NONBLOCK);
  } catch (error) {
    if (error.code === 'ENOENT') return;
    throw error;
  }
  try {
    const opened = fstatSync(fd, { bigint: true });
    const expected = Buffer.from(entry.text, 'utf8');
    if (!opened.isFile() || opened.size !== BigInt(expected.length)) throw refuse();
    regularDirectory(config);
    regularDirectory(directory);
    if (realpathSync(directory) !== directory) throw refuse();
    const named = lstatSync(entry.path, { bigint: true });
    if (!named.isFile() || named.dev !== opened.dev || named.ino !== opened.ino)
      throw refuse();
    // One extra byte detects growth while keeping arbitrary existing files bounded.
    const bytes = Buffer.alloc(expected.length + 1);
    let count = 0;
    while (count < bytes.length) {
      const size = readSync(fd, bytes, count, bytes.length - count, null);
      if (size === 0) break;
      count += size;
    }
    if (count !== expected.length || !bytes.subarray(0, count).equals(expected)) throw refuse();
  } finally {
    closeSync(fd);
  }
}
export function installAgents(project = root) {
  const target = realpathSync(project);
  const config = join(target, '.codex'),
    directory = join(config, 'agents');
  regularDirectory(config);
  regularDirectory(directory);
  const entries = definitions().map((a) => ({
    path: join(directory, a.name + '.toml'),
    text: renderAgent(a),
  }));
  // Inspect every destination before writing any; preserve unrelated/custom files.
  for (const entry of entries) inspectExistingAgent(entry, config, directory);
  mkdirSync(directory, { recursive: true });
  for (const entry of entries)
    if (!existsSync(entry.path))
      writeFileSync(entry.path, entry.text, { flag: 'wx', mode: 0o600 });
  return entries.map((e) => e.path);
}
export function launchArgs({ goal, repo = root }) {
  if (typeof goal !== 'string' || !goal.trim() || goal.length > 16000)
    throw new Error('Goalは1〜16000文字で指定してください。');
  const agents = definitions();
  const instruction = agents.find(
    (a) => a.name === 'amc',
  ).developer_instructions;
  return [
    '--cd',
    realpathSync(repo),
    '-c',
    'developer_instructions=' + JSON.stringify(instruction),
    'AMCとして次の依頼を遂行してください。独立した任務は利用可能な範囲で並列部隊へ割り当て、Goalと意図を維持してください。\n\n利用者のGoal:\n' +
      goal.trim(),
  ];
}
export function parseArgs(args) {
  const [command = 'describe', ...rest] = args;
  if (!['describe', 'install', 'run'].includes(command))
    throw new Error(
      'Use describe | install [--project <dir>] | run --goal <text> [--preview]',
    );
  const options = { command };
  for (let i = 0; i < rest.length; i++) {
    const flag = rest[i];
    if (flag === '--preview' && command === 'run' && !options.preview) {
      options.preview = true;
      continue;
    }
    if (
      !['--project', '--goal'].includes(flag) ||
      !rest[i + 1] ||
      rest[i + 1].startsWith('--')
    )
      throw new Error('Unknown or incomplete option: ' + flag);
    const key = flag.slice(2);
    if (options[key]) throw new Error('Duplicate option: ' + flag);
    options[key] = rest[++i];
  }
  if (command !== 'run' && options.goal) throw new Error('--goal requires run');
  if (command === 'describe' && options.project)
    throw new Error('--project requires install or run');
  return options;
}
export async function main(args = process.argv.slice(2)) {
  const options = parseArgs(args);
  if (options.command === 'describe') {
    console.log(
      JSON.stringify(
        {
          agents: definitions().map((a) => ({
            name: a.name,
            description: a.description,
          })),
          invoke: 'AMCで「達成したいGoal」を進めて',
          execution: 'Codex session; Web start/sync not connected',
          model: 'custom agents inherit parent; launcher uses existing CLI settings',
        },
        null,
        2,
      ),
    );
    return;
  }
  if (options.command === 'install') {
    console.log(
      JSON.stringify(
        { installed: installAgents(options.project ?? root), started: false },
        null,
        2,
      ),
    );
    return;
  }
  const repo = options.project ?? root;
  const argv = launchArgs({ goal: options.goal, repo });
  if (options.preview) {
    console.log(
      JSON.stringify({ command: 'codex', args: argv, started: false }, null, 2),
    );
    return;
  }
  // User starts this command explicitly; inherit terminal auth/model/approval.
  // No shell interpolation, no approval bypass, no scheduled/background launch.
  installAgents(repo);
  const child = spawn('codex', argv, { stdio: 'inherit', shell: false });
  await new Promise((resolveRun, reject) => {
    child.once('error', reject);
    child.once('exit', (code, signal) => {
      process.exitCode = code ?? (signal ? 130 : 1);
      resolveRun();
    });
  });
}
if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
)
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
