#!/usr/bin/env python3
"""Prepare an existing, verified OS checkout; never provision, sign or flash.

The OS checkout must already contain this clean Rock checkout at
external/rockstaros, the pinned local-action-assistant checkout and vendor
files generated by the pinned adevtool.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "os/physical/frankel-source-lock.json"
LOCAL_AI_LOCK = ROOT / "os/physical/local-action-assistant-source-lock.json"
ADDITION = ("\n# RockstarOS device bring-up; prepare-phone-build.py\n"
            "$(call inherit-product, external/rockstaros/os/physical/rockstaros.mk)\n").encode()
GIB = 1024 ** 3
LOCAL_AI_REVIEWED_FILES = {
    "LICENSE", "package.json", "src/native/modelRuntime.ts", "src/native/modelFiles.ts",
    "src/core/toolBroker.ts", "android/app/src/main/AndroidManifest.xml",
    "android/app/src/release/AndroidManifest.xml",
}


def local_ai_config(lock):
    """Validate the reviewed local-AI source identity and safety boundary."""
    if not isinstance(lock, dict):
        raise ValueError("invalid local-AI source lock")
    runtime = lock.get("runtime")
    integration = lock.get("integration")
    reviewed = lock.get("reviewedFiles")
    commit = lock.get("commit")
    checkout = lock.get("checkoutPath")
    if (lock.get("schema") != "rock-local-ai-source/1"
            or lock.get("repository") != "https://github.com/noellesugar99/local-action-assistant.git"
            or lock.get("manifestProject") != "noellesugar99/local-action-assistant"
            or not isinstance(commit, str) or re.fullmatch(r"[0-9a-f]{40}", commit) is None
            or checkout != "external/local-action-assistant"
            or lock.get("packageName") != "com.localactionassistant"
            or lock.get("version") != "0.0.1"
            or lock.get("sourceLicense") != "MIT"
            or not isinstance(runtime, dict)
            or runtime.get("engine") != "llama.rn"
            or runtime.get("version") != "0.12.9"
            or runtime.get("modelFormat") != "GGUF"
            or runtime.get("modelBundled") is not False
            or runtime.get("releaseNetworkPolicy") != "deny"
            or not isinstance(integration, dict)
            or integration.get("routeId") != "local-action-assistant"
            or integration.get("target") != "local"
            or integration.get("osBridge") not in {
                "CLIENT_AND_SERVER_SOURCE_IMPLEMENTED_NATIVE_NOT_BUILT",
                "CLIENT_AND_SERVER_NATIVE_COMPILED_EMULATOR_BOUND",
            }
            or integration.get("signedApk") not in {
                "NOT_BUILT", "UNSIGNED_RELEASE_APK_REVIEWED",
            }
            or integration.get("productPackage") not in {
                "STAGING_GENERATOR_DEFINED_NOT_BUILT",
                "STAGING_READY_NOT_IMAGE_INTEGRATED",
            }
            or not isinstance(reviewed, dict) or set(reviewed) != LOCAL_AI_REVIEWED_FILES
            or any(not isinstance(name, str) or name.startswith("/") or ".." in Path(name).parts
                   or not isinstance(digest, str) or re.fullmatch(r"[0-9a-f]{64}", digest) is None
                   for name, digest in reviewed.items())):
        raise ValueError("invalid local-AI source lock")
    return {"commit": commit, "checkoutPath": checkout,
            "manifestProject": lock["manifestProject"], "packageName": lock["packageName"],
            "engine": runtime["engine"], "engineVersion": runtime["version"],
            "reviewedFiles": dict(reviewed),
            "osBridge": integration["osBridge"]}


def verify_local_ai_source(tree):
    """Verify reviewed source only; do not build an APK or claim OS integration."""
    config = local_ai_config(json.loads(LOCAL_AI_LOCK.read_text()))
    checkout = tree / config["checkoutPath"]
    if checkout.is_symlink() or not checkout.resolve(strict=True).is_relative_to(tree):
        raise ValueError("Local-AI checkout must be a regular directory within this OS checkout.")
    if git(checkout, "rev-parse", "HEAD") != config["commit"]:
        raise ValueError("Wrong local-AI source revision.")
    if git(checkout, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Local-AI source contains local changes.")
    for name, expected in config["reviewedFiles"].items():
        source = checkout / name
        if source.is_symlink() or not source.is_file() or not source.resolve().is_relative_to(checkout):
            raise ValueError(f"Missing reviewed local-AI source file: {name}")
        if hashlib.sha256(source.read_bytes()).hexdigest() != expected:
            raise ValueError(f"Reviewed local-AI source file changed: {name}")
    package = json.loads((checkout / "package.json").read_text())
    if (package.get("version") != "0.0.1" or package.get("license") != "MIT"
            or package.get("dependencies", {}).get("llama.rn") != "0.12.9"):
        raise ValueError("Local-AI package/runtime version differs from the reviewed lock.")
    gradle = (checkout / "android/app/build.gradle").read_text()
    if not re.search(r'\bapplicationId\s+["\']com\.localactionassistant["\']', gradle):
        raise ValueError("Local-AI Android package differs from the reviewed lock.")
    release_manifest = (checkout / "android/app/src/release/AndroidManifest.xml").read_text()
    if "android.permission.INTERNET" not in release_manifest or 'tools:node="remove"' not in release_manifest:
        raise ValueError("Local-AI release variant must explicitly remove INTERNET permission.")
    tracked = git(checkout, "ls-files").splitlines()
    if any(name.lower().endswith(".gguf") for name in tracked):
        raise ValueError("The reviewed local-AI source must not bundle model weights.")
    return {"stage": "SOURCE_VERIFIED_NOT_BUILT", "commit": config["commit"],
            "checkoutPath": config["checkoutPath"], "packageName": config["packageName"],
            "engine": config["engine"], "engineVersion": config["engineVersion"],
            "modelBundled": False, "releaseNetwork": "none",
            "osBridge": config["osBridge"]}


def source_config(lock, *, require_target_confirmation=False):
    """Validate and return all build identity inputs from one source lock.

    Source preparation can inspect an unconfirmed candidate, but full builds
    must fail closed until the owner confirms the exact handset and SKU.
    """
    if not isinstance(lock, dict):
        raise ValueError("invalid phone source lock")
    device, lunch, hook = lock.get("device"), lock.get("lunch"), lock.get("hook")
    kernel = lock.get("kernel")
    platform_name = kernel.get("platform") if isinstance(kernel, dict) else None
    kernel_version = kernel.get("version") if isinstance(kernel, dict) else None
    targets = lock.get("buildTargets")
    known_skus = lock.get("knownSkus")
    confirmed_sku = lock.get("confirmedSku")
    first_flash_gate = lock.get("firstFlashGate")
    sha40 = re.compile(r"[0-9a-f]{40}")
    sha64 = re.compile(r"[0-9a-f]{64}")
    if (lock.get("schema") != "rock-phone-source/2"
            or lock.get("stage") not in {
                "SOURCE_TAG_AND_DEVICE_LAYOUT_FROZEN_RECOVERY_ARTIFACTS_PENDING",
                "FULL_BUILD_INPUTS_FROZEN",
            }
            or lock.get("manifestUrl") != "https://github.com/GrapheneOS/platform_manifest.git"
            or not isinstance(lock.get("manifestTag"), str) or not lock["manifestTag"]
            or sha40.fullmatch(lock.get("manifestTagObject", "")) is None
            or sha40.fullmatch(lock.get("manifestCommit", "")) is None
            or sha64.fullmatch(lock.get("manifestDefaultXmlSha256", "")) is None
            or sha64.fullmatch(lock.get("allowedSignersSha256", "")) is None
            or sha40.fullmatch(lock.get("adevtoolCommit", "")) is None
            or sha64.fullmatch(lock.get("hookSha256", "")) is None
            or sha40.fullmatch(kernel.get("prebuiltCommit", "") if isinstance(kernel, dict) else "") is None
            or not isinstance(device, str) or not device or re.fullmatch(r"[a-z0-9_]+", device) is None
            or not isinstance(lunch, str) or lunch != f"{device}-cur-userdebug"
            or not isinstance(hook, str)
            or hook != f"vendor/adevtool/config/mk/google_devices/device/{device}/device.mk"
            or not isinstance(platform_name, str) or re.fullmatch(r"[a-z0-9_]+", platform_name) is None
            or not isinstance(kernel_version, str) or re.fullmatch(r"[A-Za-z0-9_.-]+", kernel_version) is None
            or kernel_version in (".", "..")
            or not isinstance(targets, list) or not targets
            or any(not isinstance(target, str) or re.fullmatch(r"[A-Za-z0-9_]+(?:-[A-Za-z0-9_]+)*", target) is None
                   or target.startswith("-")
                   for target in targets)
            or not isinstance(known_skus, list) or not known_skus
            or any(not isinstance(sku, str) or re.fullmatch(r"[A-Za-z0-9_-]+", sku) is None
                   for sku in known_skus)
            or not isinstance(first_flash_gate, dict)
            or first_flash_gate.get("schema") != "avocadoos-android-first-flash-gate/1"
            or first_flash_gate.get("path") != "data/android-first-flash-gate.json"
            or not isinstance(first_flash_gate.get("passed"), bool)):
        raise ValueError("invalid lock-derived phone build inputs")
    if require_target_confirmation and (lock.get("targetConfirmedByOwner") is not True
                                        or not isinstance(confirmed_sku, str)
                                        or confirmed_sku not in known_skus):
        raise ValueError("exact phone model/SKU must be owner-confirmed before full OS build")
    if require_target_confirmation and lock.get("fullBuildInputGatePassed") is not True:
        raise ValueError(
            "full OS build input gate must include hashed recovery artifacts, vendor inventory and signing plan"
        )
    return {"device": device, "lunch": lunch, "hook": hook,
            "hook_repo_path": hook.removeprefix("vendor/adevtool/"),
            "kernel_path": f"device/google/{platform_name}-kernels/{kernel_version}",
            "required": ["build/envsetup.sh", f"vendor/google_devices/{device}/{device}.mk",
                         f"vendor/google_devices/{device}/BoardConfig.mk"],
            "buildTargets": list(targets),
            "targetConfirmedByOwner": lock.get("targetConfirmedByOwner") is True,
            "fullBuildInputGatePassed": lock.get("fullBuildInputGatePassed") is True,
            "firstFlashGatePassed": first_flash_gate["passed"],
            "confirmedSku": confirmed_sku if confirmed_sku in known_skus else None}


def build_config(*, require_target_confirmation=True):
    """Load build settings without touching the OS checkout."""
    return source_config(json.loads(LOCK.read_text()),
                         require_target_confirmation=require_target_confirmation)


def verify_hook(tree):
    """Verify the lock-pinned, already-prepared hook without changing it."""
    lock = json.loads(LOCK.read_text())
    config = source_config(lock, require_target_confirmation=True)
    tree = Path(tree).resolve(strict=True)
    if ROOT != tree / lock["rockCheckoutPath"]:
        raise ValueError("Run the copy checked out at <OS tree>/external/rockstaros.")
    hook = tree / config["hook"]
    if hook.is_symlink() or not hook.resolve().is_relative_to(tree):
        raise ValueError("Device hook must be a regular file within this OS checkout.")
    actual = hook.read_bytes()
    if not actual.endswith(ADDITION):
        raise ValueError("Device hook is not prepared from the pinned upstream bytes.")
    original = actual[:-len(ADDITION)]
    if hashlib.sha256(original).hexdigest() != lock["hookSha256"]:
        raise ValueError("Device hook differs from the pinned upstream bytes.")
    return {"hook": config["hook"], "hookSha256": hashlib.sha256(actual).hexdigest(),
            "targetConfirmedByOwner": True}


def git(directory, *args):
    return subprocess.check_output(
        ["git", "-C", str(directory), *args], stderr=subprocess.PIPE, timeout=30
    ).decode().strip()


def host_report(directory):
    """A build prerequisite check, not a hardware-boot readiness assertion."""
    memory = 0
    if sys.platform == "linux":
        memory = os.sysconf("SC_PHYS_PAGES") * os.sysconf("SC_PAGE_SIZE")
        # A container can expose host RAM that it is not allowed to use.
        for filename in ["/sys/fs/cgroup/memory.max",
                         "/sys/fs/cgroup/memory/memory.limit_in_bytes"]:
            try:
                limit = Path(filename).read_text().strip()
                if limit.isdigit():
                    memory = min(memory, int(limit))
            except FileNotFoundError:
                pass
    elif sys.platform == "darwin":
        memory = int(subprocess.check_output(["sysctl", "-n", "hw.memsize"]))
    free = shutil.disk_usage(directory).free
    checks = {
        "linux_x86_64": sys.platform == "linux" and platform.machine() in ("x86_64", "amd64"),
        "memory_at_least_64_gib": memory >= 64 * GIB,
        "free_at_least_400_gib": free >= 400 * GIB,
    }
    return {"scope": "existing GrapheneOS checkout build prerequisites, not flash readiness",
            "system": platform.system(), "architecture": platform.machine(),
            "memoryBytes": memory, "freeBytes": free, "checks": checks,
            "ready": all(checks.values()),
            "recommendation": "Dedicated x86_64 Linux; 64 GiB RAM and 400 GB free before source sync. KVM is not required to compile phone images."}


def patched_hook(content, expected_hash):
    # Retry is idempotent; an edited or newer upstream file is never overwritten.
    original = content[:-len(ADDITION)] if content.endswith(ADDITION) else content
    if hashlib.sha256(original).hexdigest() != expected_hash:
        raise ValueError("Upstream device hook differs from the pinned source; inspect it before porting.")
    return original + ADDITION


def render_manifest():
    if git(ROOT, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Commit Rock changes before generating the phone source manifest.")
    manifest = ET.Element("manifest")
    ET.SubElement(manifest, "remote", name="rock-phone", fetch="https://github.com/")
    ET.SubElement(manifest, "project", name="k999ln/rock", path="external/rockstaros",
                  remote="rock-phone", revision=git(ROOT, "rev-parse", "HEAD"))
    local_ai = local_ai_config(json.loads(LOCAL_AI_LOCK.read_text()))
    ET.SubElement(manifest, "project", name=local_ai["manifestProject"],
                  path=local_ai["checkoutPath"], remote="rock-phone",
                  revision=local_ai["commit"])
    return ET.tostring(manifest, encoding="unicode")


def manifest_structure(content):
    def node(element):
        return element.tag, element.attrib, [node(child) for child in element]
    return node(ET.fromstring(content))


def prepare(tree, allowed_signers):
    lock = json.loads(LOCK.read_text())
    config = source_config(lock)
    tree = tree.resolve(strict=True)
    if ROOT != tree / lock["rockCheckoutPath"]:
        raise ValueError("Run the copy checked out at <OS tree>/external/rockstaros.")
    if git(ROOT, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Commit Rock changes before preparing a revision-pinned OS build.")
    local = tree / ".repo/local_manifests"
    if sorted(path.name for path in local.glob("*.xml")) != ["rock-phone.xml"]:
        raise ValueError("Only the generated rock-phone.xml local manifest is allowed.")
    if manifest_structure((local / "rock-phone.xml").read_bytes()) != manifest_structure(render_manifest()):
        raise ValueError("Local manifest must only add the pinned Rock and local-AI projects, without upstream overrides.")
    manifest = tree / ".repo/manifests"
    if git(manifest, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Upstream manifest checkout contains local changes.")
    if git(manifest, "rev-parse", "HEAD") != lock["manifestCommit"]:
        raise ValueError("Wrong upstream manifest commit.")
    # Repo may use a one-include wrapper or a link to default.xml.
    selected = manifest_structure((tree / ".repo/manifest.xml").read_bytes())
    signed_default_bytes = subprocess.check_output(
        ["git", "-C", str(manifest), "show", "HEAD:default.xml"],
        stderr=subprocess.PIPE,
        timeout=30,
    )
    signed_default = signed_default_bytes.decode()
    if selected not in [manifest_structure('<manifest><include name="default.xml" /></manifest>'),
                        manifest_structure(signed_default)]:
        raise ValueError("Repo must select the signed default.xml manifest.")
    if git(manifest, "rev-parse", f"refs/tags/{lock['manifestTag']}^{{commit}}") != lock["manifestCommit"]:
        raise ValueError("Upstream tag does not resolve to the pinned manifest.")
    if git(manifest, "rev-parse", f"refs/tags/{lock['manifestTag']}") != lock["manifestTagObject"]:
        raise ValueError("Upstream tag object does not match the pinned source lock.")
    if hashlib.sha256(signed_default_bytes).hexdigest() != lock["manifestDefaultXmlSha256"]:
        raise ValueError("Pinned manifest default.xml digest does not match the verified commit.")
    if hashlib.sha256(allowed_signers.resolve(strict=True).read_bytes()).hexdigest() != lock["allowedSignersSha256"]:
        raise ValueError("GrapheneOS allowed-signers trust file differs from the audited bytes.")
    git(manifest, "-c", f"gpg.ssh.allowedSignersFile={allowed_signers.resolve(strict=True)}",
        "verify-tag", lock["manifestTag"])
    adevtool = tree / "vendor/adevtool"
    if git(adevtool, "rev-parse", "HEAD") != lock["adevtoolCommit"]:
        raise ValueError("Wrong adevtool source; do not mix firmware generations.")
    kernel = tree / config["kernel_path"]
    if git(kernel, "rev-parse", "HEAD") != lock["kernel"]["prebuiltCommit"]:
        raise ValueError("Wrong device kernel source.")
    if git(kernel, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Device kernel contains local changes.")
    local_ai = verify_local_ai_source(tree)
    # Required inputs, not proof that the entire vendor output is complete.
    for name in config["required"]:
        if not (tree / name).is_file():
            raise ValueError(f"Missing {name}; complete source sync and vendor generation first.")
    hook = tree / lock["hook"]
    if hook.is_symlink() or not hook.resolve().is_relative_to(tree):
        raise ValueError("Device hook must be a regular file within this OS checkout.")
    before = hook.read_bytes()
    after = patched_hook(before, lock["hookSha256"])
    if before != after:
        # Same-directory replacement preserves mode and avoids a truncated makefile.
        fd, temporary = tempfile.mkstemp(prefix=".rock-hook-", dir=hook.parent)
        try:
            with os.fdopen(fd, "wb") as output:
                output.write(after)
                output.flush()
                os.fsync(output.fileno())
            os.chmod(temporary, hook.stat().st_mode & 0o777)
            if hook.read_bytes() != before:
                raise ValueError("Device hook changed while preparing; retry after inspection.")
            os.replace(temporary, hook)
        finally:
            Path(temporary).unlink(missing_ok=True)
    return {"stage": "SOURCE_PREPARED_NOT_BUILT", "device": config["device"],
            "rockCommit": git(ROOT, "rev-parse", "HEAD"),
            "localAssistant": local_ai,
            "manifestCommit": lock["manifestCommit"], "adevtoolCommit": lock["adevtoolCommit"],
            "hookSha256": hashlib.sha256(after).hexdigest(), "lunch": config["lunch"],
            "targetConfirmedByOwner": config["targetConfirmedByOwner"],
            "firstFlashGatePassed": config["firstFlashGatePassed"],
            "flashReady": False,
            "remaining": ["full repo manifest -r and source review", "local-AI OS bridge and Soong packaging",
                          "signed local-AI APK and imported GGUF model", "Soong and OS image build",
                          "Hub / Wallet / Game port", "Android release signing and independent update service",
                          "first-flash signing / rollback-index / stock-recovery / Keystore-loss backup gate",
                          "exact device acceptance and recovery"]}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("manifest", help="print a local Repo manifest pinned to this clean Rock commit")
    host = commands.add_parser("host", help="read-only build capacity check")
    host.add_argument("directory", type=Path)
    commands.add_parser("build-config", help="validate owner-confirmed lock and print full-build inputs")
    local_ai = commands.add_parser("verify-local-ai", help="verify the pinned local-AI source without building it")
    local_ai.add_argument("os_tree", type=Path)
    stage = commands.add_parser("prepare", help="add the Rock product fragment to the pinned device source")
    stage.add_argument("os_tree", type=Path)
    stage.add_argument("--allowed-signers", required=True, type=Path,
                       help="GrapheneOS upstream public trust file, obtained from its official site")
    verify = commands.add_parser("verify-hook", help="verify the prepared hook immediately before a full build")
    verify.add_argument("os_tree", type=Path)
    args = parser.parse_args()
    try:
        if args.command == "manifest":
            print(render_manifest())
            return 0
        if args.command == "host":
            result = host_report(args.directory)
        elif args.command == "build-config":
            result = build_config()
            print("\t".join((result["device"], result["lunch"], result["hook"],
                             result["kernel_path"], ",".join(result["buildTargets"]))))
            return 0
        elif args.command == "verify-local-ai":
            result = verify_local_ai_source(args.os_tree.resolve(strict=True))
        elif args.command == "verify-hook":
            result = verify_hook(args.os_tree)
            print(result["hook"].removeprefix("vendor/adevtool/") + "\t" + result["hookSha256"])
            return 0
        else:
            result = prepare(args.os_tree, args.allowed_signers)
        print(json.dumps(result, indent=2))
        return 2 if args.command == "host" and not result["ready"] else 0
    except (ValueError, OSError, ET.ParseError, subprocess.SubprocessError) as error:
        # Never dump subprocess environments or unrestricted tool output.
        print(f"Phone build preparation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
