#!/usr/bin/env python3
"""Prepare an existing, verified OS checkout; never provision, sign or flash.

The OS checkout must already contain this clean Rock checkout at
external/rockstaros and vendor files generated by the pinned adevtool.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import platform
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
LOCK = ROOT / "os/physical/frankel-source-lock.json"
ADDITION = ("\n# RockstarOS device bring-up; prepare-phone-build.py\n"
            "$(call inherit-product, external/rockstaros/os/physical/rockstaros.mk)\n").encode()
GIB = 1024 ** 3


def git(directory, *args):
    return subprocess.check_output(
        ["git", "-C", str(directory), *args], stderr=subprocess.PIPE, timeout=30
    ).decode().strip()


def host_report(directory):
    """A build prerequisite check, not a hardware-boot readiness assertion."""
    memory = 0
    if sys.platform == "linux":
        memory = os.sysconf("SC_PHYS_PAGES") * os.sysconf("SC_PAGE_SIZE")
        # A container can expose host RAM that it is not allowed to use.
        for filename in ["/sys/fs/cgroup/memory.max",
                         "/sys/fs/cgroup/memory/memory.limit_in_bytes"]:
            try:
                limit = Path(filename).read_text().strip()
                if limit.isdigit():
                    memory = min(memory, int(limit))
            except FileNotFoundError:
                pass
    elif sys.platform == "darwin":
        memory = int(subprocess.check_output(["sysctl", "-n", "hw.memsize"]))
    free = shutil.disk_usage(directory).free
    checks = {
        "linux_x86_64": sys.platform == "linux" and platform.machine() in ("x86_64", "amd64"),
        "memory_at_least_32_gib": memory >= 32 * GIB,
        "free_at_least_200_gib": free >= 200 * GIB,
    }
    return {"scope": "existing GrapheneOS checkout build prerequisites, not flash readiness",
            "system": platform.system(), "architecture": platform.machine(),
            "memoryBytes": memory, "freeBytes": free, "checks": checks,
            "ready": all(checks.values()),
            "recommendation": "Dedicated x86_64 Linux; 64 GiB RAM and 400 GB free before source sync. KVM is not required to compile phone images."}


def patched_hook(content, expected_hash):
    # Retry is idempotent; an edited or newer upstream file is never overwritten.
    original = content[:-len(ADDITION)] if content.endswith(ADDITION) else content
    if hashlib.sha256(original).hexdigest() != expected_hash:
        raise ValueError("Upstream device hook differs from the pinned source; inspect it before porting.")
    return original + ADDITION


def render_manifest():
    if git(ROOT, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Commit Rock changes before generating the phone source manifest.")
    manifest = ET.Element("manifest")
    ET.SubElement(manifest, "remote", name="rock-phone", fetch="https://github.com/")
    ET.SubElement(manifest, "project", name="k999ln/rock", path="external/rockstaros",
                  remote="rock-phone", revision=git(ROOT, "rev-parse", "HEAD"))
    return ET.tostring(manifest, encoding="unicode")


def manifest_structure(content):
    def node(element):
        return element.tag, element.attrib, [node(child) for child in element]
    return node(ET.fromstring(content))


def prepare(tree, allowed_signers):
    lock = json.loads(LOCK.read_text())
    tree = tree.resolve(strict=True)
    if ROOT != tree / lock["rockCheckoutPath"]:
        raise ValueError("Run the copy checked out at <OS tree>/external/rockstaros.")
    if git(ROOT, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Commit Rock changes before preparing a revision-pinned OS build.")
    local = tree / ".repo/local_manifests"
    if sorted(path.name for path in local.glob("*.xml")) != ["rock-phone.xml"]:
        raise ValueError("Only the generated rock-phone.xml local manifest is allowed.")
    if manifest_structure((local / "rock-phone.xml").read_bytes()) != manifest_structure(render_manifest()):
        raise ValueError("Local manifest must only add this pinned Rock project, without upstream overrides.")
    manifest = tree / ".repo/manifests"
    if git(manifest, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Upstream manifest checkout contains local changes.")
    if git(manifest, "rev-parse", "HEAD") != lock["manifestCommit"]:
        raise ValueError("Wrong upstream manifest commit.")
    # Repo may use a one-include wrapper or a link to default.xml.
    selected = manifest_structure((tree / ".repo/manifest.xml").read_bytes())
    signed_default = git(manifest, "show", "HEAD:default.xml")
    if selected not in [manifest_structure('<manifest><include name="default.xml" /></manifest>'),
                        manifest_structure(signed_default)]:
        raise ValueError("Repo must select the signed default.xml manifest.")
    if git(manifest, "rev-parse", f"refs/tags/{lock['manifestTag']}^{{commit}}") != lock["manifestCommit"]:
        raise ValueError("Upstream tag does not resolve to the pinned manifest.")
    git(manifest, "-c", f"gpg.ssh.allowedSignersFile={allowed_signers.resolve(strict=True)}",
        "verify-tag", lock["manifestTag"])
    adevtool = tree / "vendor/adevtool"
    if git(adevtool, "rev-parse", "HEAD") != lock["adevtoolCommit"]:
        raise ValueError("Wrong adevtool source; do not mix firmware generations.")
    kernel = tree / "device/google/laguna-kernels/6.6"
    if git(kernel, "rev-parse", "HEAD") != lock["kernel"]["prebuiltCommit"]:
        raise ValueError("Wrong device kernel source.")
    if git(kernel, "status", "--porcelain", "--untracked-files=normal"):
        raise ValueError("Device kernel contains local changes.")
    # Required inputs, not proof that the entire vendor output is complete.
    for name in ["build/envsetup.sh", "vendor/google_devices/frankel/frankel.mk",
                 "vendor/google_devices/frankel/BoardConfig.mk"]:
        if not (tree / name).is_file():
            raise ValueError(f"Missing {name}; complete source sync and vendor generation first.")
    hook = tree / lock["hook"]
    if hook.is_symlink() or not hook.resolve().is_relative_to(tree):
        raise ValueError("Device hook must be a regular file within this OS checkout.")
    before = hook.read_bytes()
    after = patched_hook(before, lock["hookSha256"])
    if before != after:
        # Same-directory replacement preserves mode and avoids a truncated makefile.
        fd, temporary = tempfile.mkstemp(prefix=".rock-hook-", dir=hook.parent)
        try:
            with os.fdopen(fd, "wb") as output:
                output.write(after)
                output.flush()
                os.fsync(output.fileno())
            os.chmod(temporary, hook.stat().st_mode & 0o777)
            if hook.read_bytes() != before:
                raise ValueError("Device hook changed while preparing; retry after inspection.")
            os.replace(temporary, hook)
        finally:
            Path(temporary).unlink(missing_ok=True)
    return {"stage": "SOURCE_PREPARED_NOT_BUILT", "device": lock["device"],
            "rockCommit": git(ROOT, "rev-parse", "HEAD"),
            "manifestCommit": lock["manifestCommit"], "adevtoolCommit": lock["adevtoolCommit"],
            "hookSha256": hashlib.sha256(after).hexdigest(), "lunch": lock["lunch"],
            "flashReady": False,
            "remaining": ["full repo manifest -r and source review", "Soong and OS image build",
                          "Hub / Wallet / Game port", "Android release signing and independent update service",
                          "exact device acceptance and recovery"]}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("manifest", help="print a local Repo manifest pinned to this clean Rock commit")
    host = commands.add_parser("host", help="read-only build capacity check")
    host.add_argument("directory", type=Path)
    stage = commands.add_parser("prepare", help="add the Rock product fragment to the pinned device source")
    stage.add_argument("os_tree", type=Path)
    stage.add_argument("--allowed-signers", required=True, type=Path,
                       help="GrapheneOS upstream public trust file, obtained from its official site")
    args = parser.parse_args()
    try:
        if args.command == "manifest":
            print(render_manifest())
            return 0
        result = (host_report(args.directory) if args.command == "host"
                  else prepare(args.os_tree, args.allowed_signers))
        print(json.dumps(result, indent=2))
        return 2 if args.command == "host" and not result["ready"] else 0
    except (ValueError, OSError, ET.ParseError, subprocess.SubprocessError) as error:
        # Never dump subprocess environments or unrestricted tool output.
        print(f"Phone build preparation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
