import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, realpathSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderAgent } from './amc-agent.mjs';
import {
  taskBrief,
  workspaceModel,
  writeGeneratedPage,
} from './workspaces.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const read = (path) => JSON.parse(readFileSync(resolve(root, path), 'utf8'));
const header =
  '# Generated by scripts/project-bots.mjs from data/amc/project-bots.json\n';

export function projectBots() {
  const registry = read('data/amc/project-bots.json');
  const mission = read('data/mission-control.json');
  const squads = new Set(mission.squads.map((squad) => squad.id));
  const ids = new Set();
  if (
    registry.schema !== 'rock-project-bots/1' ||
    registry.repository !== 'k999ln/rock'
  )
    throw new Error('担当Bot台帳が不正です');
  for (const bot of registry.bots) {
    if (
      !/^[a-z][a-z-]+$/.test(bot.id) ||
      ids.has(bot.id) ||
      !bot.name?.trim() ||
      !bot.purpose?.trim() ||
      !bot.squads.length ||
      bot.squads.some((id) => !squads.has(id))
    )
      throw new Error('担当Botの定義が不正です');
    ids.add(bot.id);
    for (const path of [...bot.paths, ...bot.guides]) {
      if (
        relative(root, resolve(root, path)).startsWith('..') ||
        path.startsWith('/') ||
        !existsSync(resolve(root, path))
      )
        throw new Error('Botの参照が不正です: ' + path);
    }
  }
  return registry.bots;
}

export function botInstructions(bot) {
  return [
    `あなたは${bot.name}。k999ln/rockの${bot.purpose}を担当する開発Bot。`,
    '利用者の依頼を実装・検証し、成果をGitのcommitとGitHubのPRへ残す。会話の説明だけを完成物にしない。',
    `主な編集範囲: ${bot.paths.join(', ')}。共有契約の変更が必要なら影響先を特定し、taskの範囲へ含めてから行う。`,
    `読む資料: ${bot.guides.join(', ')}。参考にするAMC担当は${bot.squads.join(', ')}。Botの窓口区分はtaskAssignmentsの主担当を置き換えない。`,
    '既存のAGENTS.md、製品ベース、Mission Control、担当taskの入力・手順・合格条件・前提・executionHoldsを読む。過去の資料やモデル出力から新しい実行権限を推測しない。',
    '一回の依頼で一つの成果を扱う。依頼を既存taskへ結び、同じ成果のtaskを重複作成しない。新しい思いつきはworkspaces/IDEAS.mdへ置く。元のGoalや本人承認・task状態を直接書き換えて成功を作らない。',
    '最初にGitのmain・現在branch・未保存差分・既存PRを確認する。既存の未保存変更を保持する。他担当と同じ作業木を同時編集しない。必要なら担当task専用worktreeを作成し、基点SHAを明記する。最新mainにない先行PRが必要なら依存として明示する。',
    `作業branchはcodex/${bot.id}-<taskまたは短い目的>。mainへの直接commit、force push、履歴の破棄をしない。既存の作業branchとPRが今回の依頼に合う場合は再利用する。`,
    '対象の実装・設定・試験を変更し、必要な設計・進捗・READMEを同期する。小さい試験から実行し、npm run verifyと対象環境の検査へ進む。未実行・fixture・実機・本番は区別する。',
    '成果の差分と検証証拠を、可能なら既存amc-reviewer等の別担当へ照合させる。別担当の検収が利用できなければ未実施と記す。Bot自身の完了申告を独立検収と呼ばない。',
    '利用者がGit出力を求めている場合、今回の変更だけを通常commitし、許可されたremoteの専用branchへpushしてPRを作成または更新する。PRは成果・変更理由・試験・残課題を説明する。GitHub資格情報・ネットワーク・権限が不足する時は、手元のcommitを保持して具体的な阻害条件を返す。権限設定を勝手に広げない。',
    'Gitのauthorは既存設定を保持する。sky-bot[bot]等のGitHubアカウントを偽装しない。Bot名はPR本文の担当として記録する。GitHub App登録や別Bot資格情報はこの定義では作らない。',
    'PR作成とmain統合、Web公開、実機flash、契約、課金、実資金移動は別。後者は個別の既存承認・受入gateが必要。依頼のないmain自動merge・常時監視・無限再試行を開始しない。',
    '最後に担当Bot、task、branch、commit SHA、変更path、検証結果、独立検収の有無、PR URL、未解決、次の一手を返す。GitHub保存と手元保存を区別する。',
  ].join('\n');
}

export function renderBot(bot) {
  const agent = {
    name: `${bot.id}-bot`,
    description: `${bot.name}。${bot.purpose}の開発依頼に使う。成果は検証付きGit commitとPRへ提出する。`,
    developer_instructions: botInstructions(bot),
  };
  return header + renderAgent(agent).split('\n').slice(1).join('\n');
}

export function syncBots({ check = false } = {}) {
  const bots = projectBots();
  const directory = resolve(root, '.codex/agents');
  // This repository-managed directory is not an OS sandbox. Preserve custom files.
  if (!check) mkdirSync(directory, { recursive: true });
  if (realpathSync(directory) !== directory)
    throw new Error('Bot定義の保存先がsymlinkです');
  const pending = [];
  for (const bot of bots) {
    const path = resolve(directory, `${bot.id}-bot.toml`);
    const text = renderBot(bot);
    let existing;
    try {
      existing = readFileSync(path, 'utf8');
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
    if (existing === text) continue;
    if (existing !== undefined && !existing.startsWith(header))
      throw new Error('既存のcustom Bot定義を保持します: ' + path);
    if (check)
      throw new Error(
        'Bot定義が未同期です: ' + bot.id + ' / npm run bot:update',
      );
    pending.push({ path, text });
  }
  for (const entry of pending) writeGeneratedPage(entry.path, entry.text);
  return bots;
}

export function buildBotLaunch({ id, goal, taskId, repo = root }) {
  const bot = projectBots().find((entry) => entry.id === id);
  if (!bot) throw new Error('担当Botがありません: ' + id);
  if (typeof goal !== 'string' || !goal.trim() || goal.length > 16000)
    throw new Error('依頼は1〜16000文字で指定してください');
  let context = '';
  if (taskId) {
    const model = workspaceModel(
      read('data/mission-control.json'),
      read('data/project-status.json'),
      read('data/workspaces.json'),
    );
    const assignment = model.assignments.get(taskId);
    if (!assignment || !bot.squads.includes(assignment.primarySquad))
      throw new Error(
        'このtaskは担当Botの参照範囲外です。workコマンドで主担当を確認してください',
      );
    context =
      '\n\n既存taskの参照情報（実行保留や本人承認を解除しない）:\n' +
      taskBrief(model, taskId);
  }
  return [
    '--cd',
    realpathSync(repo),
    '-c',
    'developer_instructions=' + JSON.stringify(botInstructions(bot)),
    `${bot.name}として、次の依頼を進めて成果をGitへ保存してください。\n\n利用者の依頼:\n${goal.trim()}${context}`,
  ];
}

export function parseBotArgs(args) {
  if (!args.length || args[0] === 'list') {
    if (args.length > 1) throw new Error('listに追加引数は不要です');
    return { command: 'list' };
  }
  const [command, id, ...rest] = args;
  if (!['show', 'run'].includes(command) || !id)
    throw new Error(
      '使い方: list | show <bot> | run <bot> --goal <依頼> [--task <ID>] [--preview]',
    );
  const options = { command, id };
  for (let i = 0; i < rest.length; i++) {
    if (rest[i] === '--preview' && !options.preview) {
      options.preview = true;
      continue;
    }
    const key = { '--goal': 'goal', '--task': 'taskId' }[rest[i]];
    if (!key || options[key] || !rest[i + 1] || rest[i + 1].startsWith('--'))
      throw new Error('不正なオプション: ' + rest[i]);
    options[key] = rest[++i];
  }
  if (command === 'show' && rest.length)
    throw new Error('showに追加引数は不要です');
  return options;
}

export async function runBot(
  options,
  {
    launch = spawn,
    interactive = process.stdin.isTTY && process.stdout.isTTY,
  } = {},
) {
  const args = buildBotLaunch(options);
  syncBots({ check: true });
  if (options.preview)
    return { command: 'codex', args, started: false, githubSaved: false };
  if (!interactive)
    throw new Error(
      '対話ターミナルから実行してください。内容確認には --preview を使えます。Botは未起動です。',
    );
  const child = launch('codex', args, { stdio: 'inherit', shell: false });
  return await new Promise((resolveRun, reject) => {
    child.once('error', reject);
    child.once('exit', (code, signal) =>
      resolveRun({
        exitCode: code ?? 130,
        signal,
        started: true,
        acceptance: 'process_exit_is_not_pr_or_task_acceptance',
      }),
    );
  });
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  try {
    const args = process.argv.slice(2);
    if (args.length === 1 && ['--write', '--check'].includes(args[0]))
      console.log(
        `担当Bot: ${syncBots({ check: args[0] === '--check' }).length}定義を同期確認`,
      );
    else {
      const options = parseBotArgs(args);
      if (options.command === 'list')
        console.log(
          projectBots()
            .map((bot) => `${bot.id}: ${bot.name} — ${bot.purpose}`)
            .join('\n'),
        );
      else if (options.command === 'show') {
        const bot = projectBots().find((entry) => entry.id === options.id);
        if (!bot) throw new Error('担当Botがありません: ' + options.id);
        console.log(botInstructions(bot));
      } else {
        const result = await runBot(options);
        console.log(JSON.stringify(result, null, 2));
        if (result.exitCode) process.exitCode = result.exitCode;
      }
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
