#!/usr/bin/python3
"""Fixed read-only evidence for native remote preparation, consent and execution."""
from contextlib import closing
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import re
import sqlite3
import stat
import subprocess
import time

SOURCE = Path('/usr/libexec/rock-ui-remote-evidence.py')
if not SOURCE.is_file():
    SOURCE = Path(__file__).with_name('guest-ui-remote-evidence.py')
spec = importlib.util.spec_from_file_location('rock_ui_runner_store_observer', SOURCE)
store = importlib.util.module_from_spec(spec)
spec.loader.exec_module(store)
base = store.base
TOOL, VERSION = 'org.rockstar.remote-text', '1.0.0'
INPUT, OUTPUT = '  Native remote  \n  Actual output  ', 'Native remote\nActual output'
ENDPOINT = 'runner-linux-cloud'
DATABASE = '/data/platform/remote/remote.sqlite3'
PROOF = Path('/data/ui-runner-proof.json')
UI_KEY = re.compile(r'ui-[0-9a-f]{32}')


def remote_records_once():
    with closing(sqlite3.connect('file:' + DATABASE + '?mode=ro', uri=True, timeout=0.2)) as db:
        db.execute('PRAGMA query_only=ON')
        db.execute('BEGIN')
        db.row_factory = sqlite3.Row
        rows = [dict(row) for row in db.execute('SELECT * FROM remote_jobs ORDER BY created,key LIMIT 3')]
        cancels = [dict(row) for row in db.execute('SELECT * FROM remote_cancel_receipts LIMIT 2')]
        return rows, cancels


def remote_records():
    deadline = time.monotonic() + 15
    while True:
        try:
            return remote_records_once()
        except sqlite3.OperationalError as error:
            if getattr(error, 'sqlite_errorcode', 0) & 0xff not in (sqlite3.SQLITE_BUSY, sqlite3.SQLITE_LOCKED) or time.monotonic() >= deadline:
                raise
            time.sleep(0.1)


def expected_consent(key, package_hash):
    return {'approved': True, 'package_sha256': package_hash,
            'input_sha256': hashlib.sha256(INPUT.encode()).hexdigest(),
            'target': 'cloud', 'endpoint_id': ENDPOINT, 'key': key}


def validate_records(rows, cancels, package_hash, package):
    base.require(len(rows) <= 2 and len(cancels) <= 1, 'unexpected remote preparation or cancellation count')
    base.require(base.digest(package) == package_hash and package['manifest']['id'] == TOOL and
                 package['manifest']['version'] == VERSION and package['manifest']['schema_version'] == 3,
                 'remote package differs from the signed catalog identity')
    keys = [row['key'] for row in rows]
    base.require(len(set(keys)) == len(keys), 'remote job identities are not unique')
    for index, row in enumerate(rows):
        key = row['key']
        base.require(UI_KEY.fullmatch(key) is not None, 'remote key was not generated by native GUI')
        consent = expected_consent(key, package_hash)
        preview = json.loads(row['preview'])
        base.require(row['tool_id'] == TOOL and row['version'] == VERSION and row['package_hash'] == package_hash and
                     row['target'] == 'cloud' and row['endpoint_id'] == ENDPOINT and row['input_sha'] == consent['input_sha256'],
                     'remote identity/input/endpoint mismatch')
        base.require(row['prepare_sha'] == base.digest({'id': TOOL, 'target': 'cloud', 'text': INPUT, 'key': key}),
                     'real keyboard input differs from the prepared request')
        base.require(preview == {'prepared': True, 'approved': False, 'key': key, 'id': TOOL, 'version': VERSION,
                     'package_hash': package_hash, 'input_sha256': consent['input_sha256'], 'input_bytes': len(INPUT.encode()),
                     'target': 'cloud', 'endpoint_id': ENDPOINT, 'transport_evidence': 'pinned_tls_loopback_fixture',
                     'physical_usb': 'NOT_RUN', 'consent': consent, 'amount_minor': 0,
                     'meaning': 'preview only; no data sent and no execution accepted'}, 'exact unapproved preview differs')
        if row['state'] == 'prepared':
            base.require(row['consent'] is row['submit_sha'] is row['receipt'] is row['remote_status'] is None and
                         row['send_claimed'] == row['cancel_requested'] == 0 and row['input_text'] == INPUT and
                         json.loads(row['package']) == package, 'unapproved preparation sent or changed input')
        if index == 0:
            base.require(row['state'] in ('prepared', 'cancelled') and row['consent'] is row['submit_sha'] is row['receipt'] is None and
                         row['send_claimed'] == 0 and row['remote_status'] is None, 'discarded preparation was submitted or remotely executed')
            if row['state'] == 'cancelled':
                base.require(row['cancel_requested'] == 1 and row['package'] is row['input_text'] is None and len(cancels) == 1,
                             'discard did not prevent send and erase retained input')
                cancel = cancels[0]
                base.require(UI_KEY.fullmatch(cancel['cancel_key']) is not None and cancel['cancel_key'] not in keys and
                             cancel['request_sha'] == base.digest({'key': key, 'cancel_key': cancel['cancel_key']}) and
                             json.loads(cancel['response']) == {'accepted': True, 'operation': cancel['cancel_key'], 'key': key,
                             'before_send_claim': True, 'meaning': 'prevented before sending claim'}, 'discard receipt mismatch')
            else:
                base.require(cancels == [], 'cancellation receipt before canceled state')
        else:
            base.require(rows[0]['state'] == 'cancelled' and row['state'] in
                         ('prepared', 'queued', 'sending', 'unknown', 'accepted', 'running', 'succeeded'), 'unexpected second remote state')
            if row['state'] != 'prepared':
                base.require(json.loads(row['consent']) == consent and
                             row['submit_sha'] == base.digest({'key': key, 'consent': consent}) and
                             json.loads(row['receipt']) == {'accepted': True, 'operation': key, 'scope': 'OS remote queue',
                             'remote_accepted': False, 'meaning': 'local durable acceptance; consult remote.status for actual remote execution'},
                             'exact explicit sending consent or local acceptance receipt mismatch')
            if row['state'] == 'succeeded':
                remote = json.loads(row['remote_status'])
                request_hash = base.digest({'v': 1, 'op': 'submit', 'endpoint_id': ENDPOINT, 'key': key,
                                            'package': package, 'text': INPUT, 'consent': consent})
                receipt, execution = remote['receipt'], remote['execution']
                base.require(row['send_claimed'] == 1 and row['cancel_requested'] == 0 and row['package'] is row['input_text'] is None and
                             remote['key'] == key and remote['found'] is True and remote['state'] == 'succeeded' and remote['output'] == OUTPUT and
                             receipt['key'] == key and receipt['request_sha256'] == request_hash and receipt['endpoint_id'] == ENDPOINT and
                             receipt['actual_target'] == 'cloud' and receipt['transport_evidence'] == 'pinned_tls_loopback_fixture' and
                             receipt['physical_usb'] == 'NOT_RUN' and execution['kind'] == 'actual_linux_isolated_process' and
                             execution['socket_syscall_denied'] is True and execution['wallet_path_visible'] is False,
                             'remote actual execution, exact output or isolated executor evidence differs')
    return rows


def hub_progress(snapshot, package_hash):
    hub = snapshot['hub']
    base.require(hub['jobs'] == [] and not hub.get('jobs_truncated') and len(hub['installed']) <= 1,
                 'remote UI created a local Hub job or unexpected installation')
    audit = sorted(hub['audit'], key=lambda item: item['seq'])
    base.require(len(audit) <= 2 and [row['event'] for row in audit] == ['installed_disabled', 'enabled'][:len(audit)],
                 'native install/approval audit differs')
    if audit:
        base.require(json.loads(audit[0]['body']) == {'id': TOOL, 'version': VERSION, 'hash': package_hash}, 'wrong installed package audit')
    if len(audit) == 2:
        base.require(json.loads(audit[1]['body']) == {'id': TOOL, 'hash': package_hash} and hub['installed'][0]['enabled'] == 1,
                     'wrong native permission approval')
    return len(audit)


def validate_hub_receipts(receipts, package_hash, registry_rows=None):
    remaining, refresh = store.split_receipts(receipts, store.registry_rows() if registry_rows is None else registry_rows)
    base.require(len(remaining) == 2, 'exactly native install and approve receipts required')
    found = {}
    for row in remaining:
        key = row['key']
        base.require(UI_KEY.fullmatch(key) is not None, 'Hub receipt lacks native identity')
        candidates = {'install': {'v': 1, 'op': 'install', 'key': key, 'id': TOOL, 'version': VERSION},
                      'approve': {'v': 1, 'op': 'approve', 'key': key, 'id': TOOL, 'version': VERSION, 'approved_hash': package_hash}}
        matches = [op for op, request in candidates.items() if base.digest(request) == row['request_hash']]
        base.require(len(matches) == 1 and matches[0] not in found, 'wrong or duplicated native Hub receipt')
        op = matches[0]
        expected = {'id': TOOL, 'version': VERSION, 'hash': package_hash, 'enabled': False} if op == 'install' else {'id': TOOL, 'enabled': True}
        base.require(json.loads(row['result']) == expected, 'native Hub receipt result mismatch')
        found[op] = row
    base.require(set(found) == {'install', 'approve'}, 'missing native Hub receipt')
    return {'refresh': refresh, **found}


def observe(report):
    deadline = time.monotonic() + 360
    while True:
        try:
            snapshot = base.read_api('snapshot')['snapshot']
            environment = base.environment_evidence(store_network=True)
            rows, cancels = remote_records()
            break
        except (OSError, ValueError, AssertionError, sqlite3.Error):
            if time.monotonic() >= deadline: raise TimeoutError('native runner services did not become ready')
            time.sleep(0.5)
    cloud = next(item for item in snapshot['remote']['destinations'] if item['target'] == 'cloud')
    usb = next(item for item in snapshot['remote']['destinations'] if item['target'] == 'pc_usb')
    base.require(cloud['available'] is True and cloud['endpoint_id'] == ENDPOINT and usb['available'] is False,
                 'unexpected remote endpoints or physical USB configuration')
    base.require(rows == cancels == [] and snapshot['hub']['installed'] == snapshot['hub']['audit'] == snapshot['hub']['jobs'] == [] and
                 base.read_receipts() == [] and store.registry_rows() == [], 'native runner verification requires fresh data')
    image_ids = store.embedded_ids()
    base.require(TOOL not in image_ids and all(item['manifest']['id'] != TOOL for item in snapshot['catalog']),
                 'remote Tool must be absent from immutable OS and initial catalog')
    info = os.lstat(DATABASE)
    base.require(stat.S_ISREG(info.st_mode) and info.st_uid == info.st_gid == 1002 and stat.S_IMODE(info.st_mode) == 0o600,
                 'remote controller database ownership differs')
    wallet_hash = base.wallet_baseline(snapshot['wallet'])
    report.update(environment_initial=environment, wallet_initial=snapshot['wallet'], wallet_initial_sha256=wallet_hash,
                  immutable_catalog_ids=image_ids, initial_remote=snapshot['remote'], expected_input=INPUT, expected_output=OUTPUT,
                  observations=[], observer_mutations=0)
    base.emit('ROCK_UI_RUNNER_READY')
    package_hash, package, installed_stage, success_at = None, None, 0, None
    observed = set()
    while time.monotonic() < deadline:
        snapshot = base.read_api('snapshot')['snapshot']
        base.require(base.digest(snapshot['wallet']) == wallet_hash, 'native remote UI changed Wallet')
        base.require(snapshot['registry']['status'] != 'error', 'signed registry refresh failed')
        if package_hash is None:
            entries = [item for item in snapshot['catalog'] if item['manifest']['id'] == TOOL and item['manifest']['version'] == VERSION]
            if entries and snapshot['registry']['status'] == 'ready':
                base.require(len(entries) == 1 and snapshot['registry']['fresh'] is True, 'signed remote catalog is not fresh and unique')
                package_hash = entries[0]['hash']
                report['tool'] = {'id': TOOL, 'version': VERSION, 'package_hash': package_hash}
                base.emit('ROCK_UI_RUNNER_CATALOG')
            else:
                time.sleep(0.3); continue
        progress = hub_progress(snapshot, package_hash)
        if progress > installed_stage:
            for number in range(installed_stage + 1, progress + 1):
                base.emit(('unused', 'ROCK_UI_RUNNER_INSTALLED', 'ROCK_UI_RUNNER_APPROVED')[number])
            installed_stage = progress
        rows, cancels = remote_records()
        if rows and package is None:
            base.require(rows[0]['state'] == 'prepared' and rows[0]['package'] is not None, 'first unapproved preview was not observed')
            package = json.loads(rows[0]['package'])
        if rows:
            base.require(progress == 2, 'preparation before installed permission approval')
            validate_records(rows, cancels, package_hash, package)
            for index, row in enumerate(rows):
                state = row['state']
                marker = ('PREVIEW1' if index == 0 else 'PREVIEW2') if state == 'prepared' else 'CANCELLED' if index == 0 else 'SUBMITTED'
                if marker not in observed:
                    observed.add(marker)
                    report['observations'].append({'stage': marker, 'key': row['key'], 'state': state, 'send_claimed': row['send_claimed'], 'observed_unix': time.time()})
                    base.emit('ROCK_UI_RUNNER_' + marker, report['observations'][-1])
            if len(rows) == 2 and rows[1]['state'] == 'succeeded' and success_at is None:
                base.require({'PREVIEW1', 'CANCELLED', 'PREVIEW2', 'SUBMITTED'}.issubset(observed), 'missing independent UI approval stage observations')
                success_at = time.monotonic()
                base.emit('ROCK_UI_RUNNER_SUCCEEDED', {'key': rows[1]['key'], 'output': OUTPUT})
            if success_at is not None and time.monotonic() - success_at >= 25:
                validate_records(rows, cancels, package_hash, package)
                report.update(environment_final=base.environment_evidence(store_network=True),
                              wallet_final=snapshot['wallet'], wallet_final_sha256=base.digest(snapshot['wallet']),
                              hub=snapshot['hub'], receipts=validate_hub_receipts(base.read_receipts(), package_hash),
                              hub_receipt_rows=base.read_receipts(), registry_request_rows=store.registry_rows(),
                              remote_rows=rows, cancellation_receipts=cancels, package=package,
                              registry_final=snapshot['registry'], remote_final=snapshot['remote'], capture_grace_seconds=25)
                base.require(report['environment_final']['processes'] == environment['processes'], 'native service restarted during GUI flow')
                report['status'] = 'PASS'
                return
        time.sleep(0.3)
    raise TimeoutError('native remote GUI flow did not finish')


def main():
    if os.getuid() != 0 or os.geteuid() != 0 or os.uname().machine != 'aarch64' or 'rock.ui.runner.verify=1' not in Path('/proc/cmdline').read_text().split():
        raise SystemExit('requires explicitly flagged root ARM64 native runner verification boot')
    report = {'schema': 'rock-native-runner-ui-proof/1', 'status': 'FAIL', 'scope': 'native UI and owned VM TLS fixture only',
              'blackberry': 'NOT_RUN', 'physical_usb': 'NOT_RUN', 'production_cloud': 'NOT_RUN', 'real_money': 'NOT_RUN', 'started_unix': time.time()}
    try:
        observe(report)
    except BaseException as error:
        report.update(status='FAIL', error=type(error).__name__ + ': ' + str(error))
    report['finished_unix'] = time.time()
    try:
        base.PROOF = PROOF
        base.persist(report)
    except BaseException as error:
        report.update(status='FAIL', persistence_error=str(error))
    base.emit('ROCK_UI_RUNNER_PROOF', report)
    base.emit('ROCK_UI_RUNNER_' + report['status'])
    os.sync()
    subprocess.run(['/sbin/poweroff', '-f'], check=False)
    return 0 if report['status'] == 'PASS' else 1


if __name__ == '__main__':
    raise SystemExit(main())
