plugins { id 'com.android.application' }

android {
    namespace 'dev.rock.jev.provider'
    compileSdk 35
    defaultConfig {
        applicationId 'dev.rock.jev.provider'
        minSdk 35
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_11; targetCompatibility JavaVersion.VERSION_11 }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20250107'
}
